project:
  type: book
  output-dir: docs

book:
  title: "Survey Design and Analysis"
  author: "Michael Foley"
  date: today
  cover-image: images/survey-says.png
  chapters:
    - index.qmd
    - part: Design
      chapters:
      - survey_projects.qmd
      - item_selection.qmd
      - sampling_strategy.qmd
    - part: "Analysis"
      chapters:
      - data_preparation.qmd
      - descriptive-stats.qmd
      - statistical-tests.qmd
      - 07-modeling.qmd
    - part: "Case Studies"
      chapters: 
      - 08-best_worst_scaling.qmd
      - 11-other.qmd
    - part: "Case Studies"
      chapters: 
      - 09-case_study_nhanes.qmd
      - 10-case_study_ncsr.qmd
    - 12-references.qmd

bibliography: references.bib

execute: 
  echo: true
  message: false
  error: false
  warning: false

format:
  html:
    theme: cosmo
    toc-title: "On this page"
    toc-depth: 4
    code-tools: true
    code-overflow: scroll
    code-fold: false
    fig-cap-location: top
  pdf:
    documentclass: scrreprt

editor: source

language: 
  code-summary: "Show the code"
