project:
  type: book
  output-dir: docs

book:
  title: "Survey Design and Analysis"
  author: "Michael Foley"
  date: today
  cover-image: cover.png
  chapters:
    - index.qmd
    - 01-item_selection.qmd
    - 02-sample_size.qmd
    - 03-statistical_power.qmd
    - 04-analysis.qmd
    - 05-simple_random_sample.qmd
    - 06-stratified_random_sample.qmd
    - 07-best_worst_scaling.qmd
    - 08-case_study.qmd
    - 10-references.qmd

bibliography: references.bib

execute: 
  echo: true
  message: false
  error: false
  warning: false

format:
  html:
    theme: cosmo
    toc-title: "On this page"
    toc-depth: 4
    code-tools: true
    code-overflow: scroll
    code-fold: show
  pdf:
    documentclass: scrreprt

editor: source

language: 
  code-summary: "Show the code"
