<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6.4 Case Study: Pearson, Spearman, Kendall | Statistical Inference</title>
  <meta name="description" content="Notes cobbled together from books, online classes, etc. to be used as quick reference for common work projects." />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content="6.4 Case Study: Pearson, Spearman, Kendall | Statistical Inference" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Notes cobbled together from books, online classes, etc. to be used as quick reference for common work projects." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6.4 Case Study: Pearson, Spearman, Kendall | Statistical Inference" />
  
  <meta name="twitter:description" content="Notes cobbled together from books, online classes, etc. to be used as quick reference for common work projects." />
  

<meta name="author" content="Michael Foley" />


<meta name="date" content="2023-10-31" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="kendall.html"/>
<link rel="next" href="chisq-independence.html"/>
<script src="assets/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="assets/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="assets/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="assets/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="assets/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="assets/tabwid-1.1.3/tabwid.css" rel="stylesheet" />
<script src="assets/tabwid-1.1.3/tabwid.js"></script>
<script src="assets/kePrint-0.0.1/kePrint.js"></script>
<link href="assets/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="frequentist-statistics.html"><a href="frequentist-statistics.html"><i class="fa fa-check"></i><b>1</b> Frequentist Statistics</a>
<ul>
<li class="chapter" data-level="1.1" data-path="central-tendancy-and-dispersion.html"><a href="central-tendancy-and-dispersion.html"><i class="fa fa-check"></i><b>1.1</b> Central Tendancy and Dispersion</a></li>
<li class="chapter" data-level="1.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>1.2</b> Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#type-i-and-ii-errors"><i class="fa fa-check"></i>Type I and II Errors</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#statistical-power"><i class="fa fa-check"></i>Statistical Power</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#what-p-values-would-you-expect"><i class="fa fa-check"></i>What p-values would you expect?</a></li>
<li class="chapter" data-level="1.2.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#further-reading"><i class="fa fa-check"></i><b>1.2.1</b> Further Reading</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="likelihood-statistics.html"><a href="likelihood-statistics.html"><i class="fa fa-check"></i><b>2</b> Likelihood Statistics</a>
<ul>
<li class="chapter" data-level="2.1" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html"><i class="fa fa-check"></i><b>2.1</b> Maximum Likelihood Estimation</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="bayesian-statistics.html"><a href="bayesian-statistics.html"><i class="fa fa-check"></i><b>3</b> Bayesian Statistics</a>
<ul>
<li class="chapter" data-level="3.1" data-path="bayes-theorem.html"><a href="bayes-theorem.html"><i class="fa fa-check"></i><b>3.1</b> Bayes’ Theorem</a></li>
<li class="chapter" data-level="3.2" data-path="bayesian-inference.html"><a href="bayesian-inference.html"><i class="fa fa-check"></i><b>3.2</b> Bayesian Inference</a></li>
<li class="chapter" data-level="3.3" data-path="gamma-poisson-and-estimating-counts.html"><a href="gamma-poisson-and-estimating-counts.html"><i class="fa fa-check"></i><b>3.3</b> Gamma Poisson and Estimating Counts</a></li>
<li class="chapter" data-level="3.4" data-path="normal-and-estimating-means.html"><a href="normal-and-estimating-means.html"><i class="fa fa-check"></i><b>3.4</b> Normal and Estimating Means</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="normal-and-estimating-means.html"><a href="normal-and-estimating-means.html#population-estimate"><i class="fa fa-check"></i><b>3.4.1</b> Population Estimate</a></li>
<li class="chapter" data-level="3.4.2" data-path="normal-and-estimating-means.html"><a href="normal-and-estimating-means.html#regression"><i class="fa fa-check"></i><b>3.4.2</b> Regression</a></li>
<li class="chapter" data-level="3.4.3" data-path="normal-and-estimating-means.html"><a href="normal-and-estimating-means.html#change-point-regression"><i class="fa fa-check"></i><b>3.4.3</b> Change Point Regression</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="beta-binomial-and-estimating-proportions.html"><a href="beta-binomial-and-estimating-proportions.html"><i class="fa fa-check"></i><b>3.5</b> Beta Binomial and Estimating Proportions</a></li>
<li class="chapter" data-level="3.6" data-path="zero-inflation-and-latent-variables.html"><a href="zero-inflation-and-latent-variables.html"><i class="fa fa-check"></i><b>3.6</b> Zero-Inflation and Latent Variables</a></li>
<li class="chapter" data-level="3.7" data-path="dic.html"><a href="dic.html"><i class="fa fa-check"></i><b>3.7</b> DIC</a></li>
<li class="chapter" data-level="3.8" data-path="monte-carlo-integration.html"><a href="monte-carlo-integration.html"><i class="fa fa-check"></i><b>3.8</b> Monte Carlo Integration</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="monte-carlo-integration.html"><a href="monte-carlo-integration.html#inverse-sampling"><i class="fa fa-check"></i><b>3.8.1</b> Inverse Sampling</a></li>
<li class="chapter" data-level="3.8.2" data-path="monte-carlo-integration.html"><a href="monte-carlo-integration.html#rejection-sampling"><i class="fa fa-check"></i><b>3.8.2</b> Rejection Sampling</a></li>
<li class="chapter" data-level="3.8.3" data-path="monte-carlo-integration.html"><a href="monte-carlo-integration.html#importance-sampling"><i class="fa fa-check"></i><b>3.8.3</b> Importance Sampling</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="metropolis-hastings.html"><a href="metropolis-hastings.html"><i class="fa fa-check"></i><b>3.9</b> Metropolis-Hastings</a></li>
<li class="chapter" data-level="3.10" data-path="appendix-gentle-introduction.html"><a href="appendix-gentle-introduction.html"><i class="fa fa-check"></i><b>3.10</b> Appendix: Gentle Introduction</a></li>
<li class="chapter" data-level="3.11" data-path="appendix-bayes-factors.html"><a href="appendix-bayes-factors.html"><i class="fa fa-check"></i><b>3.11</b> Appendix: Bayes Factors</a></li>
<li class="chapter" data-level="3.12" data-path="further-reading-1.html"><a href="further-reading-1.html"><i class="fa fa-check"></i><b>3.12</b> Further Reading</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="one-sample.html"><a href="one-sample.html"><i class="fa fa-check"></i><b>4</b> One-Sample</a>
<ul>
<li class="chapter" data-level="4.1" data-path="one-sample-mean-z-test.html"><a href="one-sample-mean-z-test.html"><i class="fa fa-check"></i><b>4.1</b> One-Sample Mean z Test</a></li>
<li class="chapter" data-level="4.2" data-path="one-sample-mean-t-test.html"><a href="one-sample-mean-t-test.html"><i class="fa fa-check"></i><b>4.2</b> One-Sample Mean t Test</a></li>
<li class="chapter" data-level="4.3" data-path="one-sample-median-wilcoxon-test.html"><a href="one-sample-median-wilcoxon-test.html"><i class="fa fa-check"></i><b>4.3</b> One-Sample Median Wilcoxon Test</a></li>
<li class="chapter" data-level="4.4" data-path="chi-squared-goodness-of-fit-test.html"><a href="chi-squared-goodness-of-fit-test.html"><i class="fa fa-check"></i><b>4.4</b> Chi-Squared Goodness-of-Fit Test</a></li>
<li class="chapter" data-level="4.5" data-path="g-test.html"><a href="g-test.html"><i class="fa fa-check"></i><b>4.5</b> G-Test</a></li>
<li class="chapter" data-level="4.6" data-path="one-sample-poisson-test.html"><a href="one-sample-poisson-test.html"><i class="fa fa-check"></i><b>4.6</b> One-Sample Poisson Test</a></li>
<li class="chapter" data-level="4.7" data-path="exact-binomial-test.html"><a href="exact-binomial-test.html"><i class="fa fa-check"></i><b>4.7</b> Exact Binomial Test</a></li>
<li class="chapter" data-level="4.8" data-path="one-sample-proportion-z-test.html"><a href="one-sample-proportion-z-test.html"><i class="fa fa-check"></i><b>4.8</b> One-Sample Proportion z Test</a></li>
<li class="chapter" data-level="4.9" data-path="sample-t-test-for-categorical-var.html"><a href="sample-t-test-for-categorical-var.html"><i class="fa fa-check"></i><b>4.9</b> 1 sample t Test for Categorical Var</a></li>
<li class="chapter" data-level="4.10" data-path="wilcoxon-1-sample-median-test-for-categorical-var.html"><a href="wilcoxon-1-sample-median-test-for-categorical-var.html"><i class="fa fa-check"></i><b>4.10</b> Wilcoxon 1-Sample Median Test for Categorical Var</a></li>
<li class="chapter" data-level="4.11" data-path="multivariate-statistics.html"><a href="multivariate-statistics.html"><i class="fa fa-check"></i><b>4.11</b> Multivariate Statistics</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="group-differences.html"><a href="group-differences.html"><i class="fa fa-check"></i><b>5</b> Group Differences</a>
<ul>
<li class="chapter" data-level="5.1" data-path="ttest.html"><a href="ttest.html"><i class="fa fa-check"></i><b>5.1</b> Independent Samples t-Test</a></li>
<li class="chapter" data-level="5.2" data-path="wilcoxonranksum.html"><a href="wilcoxonranksum.html"><i class="fa fa-check"></i><b>5.2</b> Wilcoxon Rank Sum Test</a></li>
<li class="chapter" data-level="" data-path="case-study-1.html"><a href="case-study-1.html"><i class="fa fa-check"></i>Case Study 1</a></li>
<li class="chapter" data-level="5.3" data-path="pairedttest.html"><a href="pairedttest.html"><i class="fa fa-check"></i><b>5.3</b> Paired Samples t-Test</a></li>
<li class="chapter" data-level="5.4" data-path="wilcoxonsignedrank.html"><a href="wilcoxonsignedrank.html"><i class="fa fa-check"></i><b>5.4</b> Wilcoxon Signed-Rank Test</a>
<ul>
<li class="chapter" data-level="" data-path="wilcoxonsignedrank.html"><a href="wilcoxonsignedrank.html#sign-test"><i class="fa fa-check"></i>Sign Test</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="case-study-2.html"><a href="case-study-2.html"><i class="fa fa-check"></i>Case Study 2</a></li>
<li class="chapter" data-level="5.5" data-path="onewayanova.html"><a href="onewayanova.html"><i class="fa fa-check"></i><b>5.5</b> One-way ANOVA</a></li>
<li class="chapter" data-level="5.6" data-path="kw.html"><a href="kw.html"><i class="fa fa-check"></i><b>5.6</b> Kruskal–Wallis Test</a></li>
<li class="chapter" data-level="" data-path="groupdiffscs3.html"><a href="groupdiffscs3.html"><i class="fa fa-check"></i>Case Study 3</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="groupdiffscs3.html"><a href="groupdiffscs3.html#assumptions"><i class="fa fa-check"></i><b>5.6.1</b> Assumptions</a></li>
<li class="chapter" data-level="5.6.2" data-path="groupdiffscs3.html"><a href="groupdiffscs3.html#anova"><i class="fa fa-check"></i><b>5.6.2</b> ANOVA</a></li>
<li class="chapter" data-level="5.6.3" data-path="groupdiffscs3.html"><a href="groupdiffscs3.html#kruskal-wallis-test"><i class="fa fa-check"></i><b>5.6.3</b> Kruskal-Wallis Test</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="chisqhomogeneity.html"><a href="chisqhomogeneity.html"><i class="fa fa-check"></i><b>5.7</b> Chi-Square Test of Homogeneity</a></li>
<li class="chapter" data-level="5.8" data-path="fisherexact.html"><a href="fisherexact.html"><i class="fa fa-check"></i><b>5.8</b> Fisher’s Exact Test</a></li>
<li class="chapter" data-level="" data-path="case-study-4.html"><a href="case-study-4.html"><i class="fa fa-check"></i>Case Study 4</a></li>
<li class="chapter" data-level="5.9" data-path="pairwiseproptest.html"><a href="pairwiseproptest.html"><i class="fa fa-check"></i><b>5.9</b> Pairwise Prop Test</a></li>
<li class="chapter" data-level="5.10" data-path="mcnemar.html"><a href="mcnemar.html"><i class="fa fa-check"></i><b>5.10</b> McNemar’s Test</a>
<ul>
<li class="chapter" data-level="5.10.1" data-path="mcnemar.html"><a href="mcnemar.html#manova"><i class="fa fa-check"></i><b>5.10.1</b> MANOVA</a></li>
<li class="chapter" data-level="5.10.2" data-path="mcnemar.html"><a href="mcnemar.html#multiple-variance-comparison-f-test"><i class="fa fa-check"></i><b>5.10.2</b> Multiple Variance Comparison F Test</a></li>
<li class="chapter" data-level="5.10.3" data-path="mcnemar.html"><a href="mcnemar.html#example-5"><i class="fa fa-check"></i><b>5.10.3</b> Example</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="association.html"><a href="association.html"><i class="fa fa-check"></i><b>6</b> Association</a>
<ul>
<li class="chapter" data-level="6.1" data-path="pearson.html"><a href="pearson.html"><i class="fa fa-check"></i><b>6.1</b> Pearson’s Correlation</a></li>
<li class="chapter" data-level="6.2" data-path="spearman.html"><a href="spearman.html"><i class="fa fa-check"></i><b>6.2</b> Spearman’s Rho</a></li>
<li class="chapter" data-level="6.3" data-path="kendall.html"><a href="kendall.html"><i class="fa fa-check"></i><b>6.3</b> Kendal’s Tau</a></li>
<li class="chapter" data-level="6.4" data-path="case-study-pearson-spearman-kendall.html"><a href="case-study-pearson-spearman-kendall.html"><i class="fa fa-check"></i><b>6.4</b> Case Study: Pearson, Spearman, Kendall</a></li>
<li class="chapter" data-level="6.5" data-path="chisq-independence.html"><a href="chisq-independence.html"><i class="fa fa-check"></i><b>6.5</b> Chi-Square Test of Independence</a></li>
<li class="chapter" data-level="6.6" data-path="fisher-exact.html"><a href="fisher-exact.html"><i class="fa fa-check"></i><b>6.6</b> Fisher’s Exact Test</a></li>
<li class="chapter" data-level="6.7" data-path="case-study-chi-square-fisher.html"><a href="case-study-chi-square-fisher.html"><i class="fa fa-check"></i><b>6.7</b> Case Study: Chi-Square, Fisher</a></li>
<li class="chapter" data-level="6.8" data-path="kruskals-lambda.html"><a href="kruskals-lambda.html"><i class="fa fa-check"></i><b>6.8</b> Kruskal’s Lambda</a></li>
<li class="chapter" data-level="6.9" data-path="relative-risk.html"><a href="relative-risk.html"><i class="fa fa-check"></i><b>6.9</b> Relative Risk</a></li>
<li class="chapter" data-level="6.10" data-path="odds-ratio.html"><a href="odds-ratio.html"><i class="fa fa-check"></i><b>6.10</b> Odds Ratio</a></li>
<li class="chapter" data-level="6.11" data-path="partial-correlation.html"><a href="partial-correlation.html"><i class="fa fa-check"></i><b>6.11</b> Partial Correlation</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="matrix-algebra.html"><a href="matrix-algebra.html"><i class="fa fa-check"></i><b>7</b> Matrix Algebra</a>
<ul>
<li class="chapter" data-level="7.1" data-path="central-tendancy-dispersion-and-association.html"><a href="central-tendancy-dispersion-and-association.html"><i class="fa fa-check"></i><b>7.1</b> Central Tendancy, Dispersion, and Association</a></li>
<li class="chapter" data-level="7.2" data-path="linear-transformations.html"><a href="linear-transformations.html"><i class="fa fa-check"></i><b>7.2</b> Linear Transformations</a></li>
<li class="chapter" data-level="7.3" data-path="multivariate-normal-distribution.html"><a href="multivariate-normal-distribution.html"><i class="fa fa-check"></i><b>7.3</b> Multivariate Normal Distribution</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Inference</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="case-study-pearson-spearman-kendall" class="section level2 hasAnchor" number="6.4">
<h2><span class="header-section-number">6.4</span> Case Study: Pearson, Spearman, Kendall<a href="case-study-pearson-spearman-kendall.html#case-study-pearson-spearman-kendall" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This case study works with two data sets. <code>dat1</code> is composed of two continuous variables; <code>dat2</code> is composed of two ordinal variables.</p>
<p>A researcher investigates the relationship between <code>cholesterol</code> concentration and time spent watching TV, <code>time_tv</code>, in <em>n</em> = 100 otherwise healthy 45 to 65 year old men (<code>dat1</code>). This data set will meet the conditions for Pearson, so we try all three tests on it.</p>
<p>A researcher investigates the relationship between the level of agreement with the statement “<em>Taxes are too high</em>” (<code>tax_too_high</code>, four level ordinal) and participant <code>income</code> level (three level ordinal) (<code>dat2</code>). The ordinal variables rule out Pearson, leaving Spearman and Kendall.</p>
<div id="conditions-7" class="section level4 unnumbered hasAnchor">
<h4>Conditions<a href="case-study-pearson-spearman-kendall.html#conditions-7" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Pearson’s correlation applies when X and Y are continuous (interval or ratio) paired variables with 1) a linear relationship that 2) has no significant outliers, and 3) are bivariate normal. Spearman’s rho and Kendall’s tau only require that X and Y be at least ordinal with 1) a monotonically increasing or decreasing relationship.</p>
<ol style="list-style-type: decimal">
<li><strong>Linearity</strong> and <strong>Monotonicity</strong>. A visual inspection of a scatterplot should find a linear relationship (Pearson) or monotonic relationship (Spearman and Kendall).</li>
</ol>
<p>Pearson’s correlation additionall requires</p>
<ol start="2" style="list-style-type: decimal">
<li><strong>No Outliers</strong>. Identify outliers with the scatterplot.</li>
<li><strong>Normality</strong>. Bivariate normality is difficult to assess. Instead, check that each variable is individually normally distributed. Use the Shapiro-Wilk test.</li>
</ol>
<div id="linearity-monotonicity" class="section level5 unnumbered hasAnchor">
<h5>Linearity / Monotonicity<a href="case-study-pearson-spearman-kendall.html#linearity-monotonicity" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Assess linearity and monotonicity with a scatter plot. <code>dat1</code> is plotted on the left in Figure <a href="case-study-pearson-spearman-kendall.html#fig:ccscatter">6.1</a>. A second version that fails the linearity test is shown to the right. If the linear relationship assumption fails, consider transforming the variable instead of reverting to Spearman or Kendall.</p>
<div class="figure"><span style="display:block;" id="fig:ccscatter"></span>
<img src="statistics_files/figure-html/ccscatter-1.png" alt="The left scatter plot is `dat1`. It meets Pearson's linearity condition. A second version at right illustrates what a failure might look like." width="720" />
<p class="caption">
Figure 6.1: The left scatter plot is <code>dat1</code>. It meets Pearson’s linearity condition. A second version at right illustrates what a failure might look like.
</p>
</div>
<p>The ordinal variable data set <code>dat2</code> is plotted in Figure <a href="case-study-pearson-spearman-kendall.html#fig:ooscatter">6.2</a>.</p>
<div class="figure"><span style="display:block;" id="fig:ooscatter"></span>
<img src="statistics_files/figure-html/ooscatter-1.png" alt="`dat2` meets the mononicity assumption for Spearman's rho and Kendall's tau." width="528" />
<p class="caption">
Figure 6.2: <code>dat2</code> meets the mononicity assumption for Spearman’s rho and Kendall’s tau.
</p>
</div>
</div>
<div id="no-outliers" class="section level5 unnumbered hasAnchor">
<h5>No Outliers<a href="case-study-pearson-spearman-kendall.html#no-outliers" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Pearson’s correlation requires no outliers. Both plots in Figure <a href="case-study-pearson-spearman-kendall.html#fig:ccscatter">6.1</a> are free of outliers. If there were outliers, check whether they are data entry errors or measurement errors and fix or discard them. If the outliers are genuine, leave them in if they do not affect the conclusion. You can also try tranforming the variable. Failing all that, revert to the Spearman’s rho or Kendall’s tau.</p>
</div>
<div id="bivariate-normality" class="section level5 unnumbered hasAnchor">
<h5>Bivariate Normality<a href="case-study-pearson-spearman-kendall.html#bivariate-normality" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Bivariate normality is difficult to assess. If two variables are bivariate normal, they will each be individually normal as well. That’s the best you can hope to check for. Use the Shapiro-Wilk test.</p>
<div class="sourceCode" id="cb315"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb315-1"><a href="case-study-pearson-spearman-kendall.html#cb315-1" tabindex="-1"></a><span class="fu">shapiro.test</span>(cs<span class="sc">$</span>dat1<span class="sc">$</span>time_tv)</span>
<span id="cb315-2"><a href="case-study-pearson-spearman-kendall.html#cb315-2" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb315-3"><a href="case-study-pearson-spearman-kendall.html#cb315-3" tabindex="-1"></a><span class="do">##  Shapiro-Wilk normality test</span></span>
<span id="cb315-4"><a href="case-study-pearson-spearman-kendall.html#cb315-4" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb315-5"><a href="case-study-pearson-spearman-kendall.html#cb315-5" tabindex="-1"></a><span class="do">## data:  cs$dat1$time_tv</span></span>
<span id="cb315-6"><a href="case-study-pearson-spearman-kendall.html#cb315-6" tabindex="-1"></a><span class="do">## W = 0.97989, p-value = 0.1304</span></span>
<span id="cb315-7"><a href="case-study-pearson-spearman-kendall.html#cb315-7" tabindex="-1"></a><span class="fu">shapiro.test</span>(cs<span class="sc">$</span>dat1<span class="sc">$</span>cholesterol)</span>
<span id="cb315-8"><a href="case-study-pearson-spearman-kendall.html#cb315-8" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb315-9"><a href="case-study-pearson-spearman-kendall.html#cb315-9" tabindex="-1"></a><span class="do">##  Shapiro-Wilk normality test</span></span>
<span id="cb315-10"><a href="case-study-pearson-spearman-kendall.html#cb315-10" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb315-11"><a href="case-study-pearson-spearman-kendall.html#cb315-11" tabindex="-1"></a><span class="do">## data:  cs$dat1$cholesterol</span></span>
<span id="cb315-12"><a href="case-study-pearson-spearman-kendall.html#cb315-12" tabindex="-1"></a><span class="do">## W = 0.97594, p-value = 0.06387</span></span></code></pre></div>
<p>If a variable is not normally distributed, you can transform it, carry on regardless since the Pearson correlation is fairly robust to deviations from normality, or revert to Spearman and Kendall.</p>
</div>
</div>
<div id="test-3" class="section level4 unnumbered hasAnchor">
<h4>Test<a href="case-study-pearson-spearman-kendall.html#test-3" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Calculate Pearson’s correlation, Spearman’s rho, or Kendall’s tau. <code>dat</code> meets the assumptions for Pearson’s correlation, but try Spearman’s rho and Kendall’s tau too, just to see how close they come to Pearson. <code>dat2</code> only meets the assumptions for Spearman and Kendall.</p>
<div id="pearsons-correlation" class="section level5 unnumbered hasAnchor">
<h5>Pearson’s Correlation<a href="case-study-pearson-spearman-kendall.html#pearsons-correlation" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p><code>dat1</code> met the conditions for Pearson’s correlation.</p>
<div class="sourceCode" id="cb316"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb316-1"><a href="case-study-pearson-spearman-kendall.html#cb316-1" tabindex="-1"></a>(cs<span class="sc">$</span>cc_pearson <span class="ot">&lt;-</span> </span>
<span id="cb316-2"><a href="case-study-pearson-spearman-kendall.html#cb316-2" tabindex="-1"></a>  <span class="fu">cor.test</span>(cs<span class="sc">$</span>dat1<span class="sc">$</span>cholesterol, cs<span class="sc">$</span>dat1<span class="sc">$</span>time_tv, <span class="at">method =</span> <span class="st">&quot;pearson&quot;</span>)</span>
<span id="cb316-3"><a href="case-study-pearson-spearman-kendall.html#cb316-3" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  cs$dat1$cholesterol and cs$dat1$time_tv
## t = 3.9542, df = 98, p-value = 0.0001451
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.1882387 0.5288295
## sample estimates:
##       cor 
## 0.3709418</code></pre>
<p><em>r</em> = 0.37 falls in the range of a “moderate” linear relationship. <span class="math inline">\(r^2\)</span> = 14% is the coefficient of determination. Interpret it as the percent of variability in one variable that is explained by the other. If you are not testing a hypothesis (HO: <span class="math inline">\(\rho \ne 0\)</span>), you can report just report <em>r</em>. Otherwise, include the <em>p</em>-value. Report your results like this:</p>
<blockquote>
<p>A Pearson’s product-moment correlation was run to assess the relationship between cholesterol concentration and daily time spent watching TV in males aged 45 to 65 years. One hundred participants were recruited.</p>
<p>Preliminary analyses showed the relationship to be linear with both variables normally distributed, as assessed by Shapiro-Wilk’s test (p &gt; .05), and there were no outliers.</p>
<p>There was a statistically significant, moderate positive correlation between daily time spent watching TV and cholesterol concentration, <em>r</em>(98) = 0.37, p &lt; .0005, with time spent watching TV explaining 14% of the variation in cholesterol concentration.</p>
</blockquote>
<p>You wouldn’t use Spearman’s rho or Kendall’s tau here since the more precise Pearson’s correlation is available. But just out of curiosity, here are the correlations using those two measures.</p>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb318-1"><a href="case-study-pearson-spearman-kendall.html#cb318-1" tabindex="-1"></a><span class="fu">cor</span>(cs<span class="sc">$</span>dat1<span class="sc">$</span>cholesterol, cs<span class="sc">$</span>dat1<span class="sc">$</span>time_tv, <span class="at">method =</span> <span class="st">&quot;kendall&quot;</span>)</span>
<span id="cb318-2"><a href="case-study-pearson-spearman-kendall.html#cb318-2" tabindex="-1"></a><span class="do">## [1] 0.2383971</span></span>
<span id="cb318-3"><a href="case-study-pearson-spearman-kendall.html#cb318-3" tabindex="-1"></a><span class="fu">cor</span>(cs<span class="sc">$</span>dat1<span class="sc">$</span>cholesterol, cs<span class="sc">$</span>dat1<span class="sc">$</span>time_tv, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>)</span>
<span id="cb318-4"><a href="case-study-pearson-spearman-kendall.html#cb318-4" tabindex="-1"></a><span class="do">## [1] 0.3322122</span></span></code></pre></div>
<p>Both Kendall and Spearman produced more conservative estimates of the strength of the relationship - Kendall especially so.</p>
<p>You probably wouldn’t use linear regression here either because it describes the linear relationship between a <em>response</em> variable and changes to an independent <em>explanatory</em> variable. Even though we are reluctant to interpret a regression model in terms of causality, that is what is implied the formulation <code>y ~ x</code> and independence assumption in of X. Nevertheless, correlation and regression are related. The slope term in a simple linear regression of the normalized values equals the Pearson correlation.</p>
<div class="sourceCode" id="cb319"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb319-1"><a href="case-study-pearson-spearman-kendall.html#cb319-1" tabindex="-1"></a><span class="fu">lm</span>(</span>
<span id="cb319-2"><a href="case-study-pearson-spearman-kendall.html#cb319-2" tabindex="-1"></a>  y <span class="sc">~</span> x, </span>
<span id="cb319-3"><a href="case-study-pearson-spearman-kendall.html#cb319-3" tabindex="-1"></a>  <span class="at">data =</span> cs<span class="sc">$</span>dat1 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">y =</span> <span class="fu">scale</span>(cholesterol), <span class="at">x =</span> <span class="fu">scale</span>(time_tv))</span>
<span id="cb319-4"><a href="case-study-pearson-spearman-kendall.html#cb319-4" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x, data = cs$dat1 %&gt;% mutate(y = scale(cholesterol), 
##     x = scale(time_tv)))
## 
## Coefficients:
## (Intercept)            x  
##  -3.092e-16    3.709e-01</code></pre>
</div>
<div id="spearmans-rho" class="section level5 unnumbered hasAnchor">
<h5>Spearman’s Rho<a href="case-study-pearson-spearman-kendall.html#spearmans-rho" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Data set <code>dat2</code> did not meet the conditions for Pearson’s correlation, so use Spearman’s rho and/or Kendall’s tau.</p>
<p>Start with Spearman’s rho. Recall that Spearman’s rho is just the Pearson correlation applied to the ranks. Recall also that the Pearson’s correlation is just the covariance divided by the product of the standard deviations. You can quickly calculate it by hand.</p>
<div class="sourceCode" id="cb321"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb321-1"><a href="case-study-pearson-spearman-kendall.html#cb321-1" tabindex="-1"></a><span class="fu">cov</span>(<span class="fu">rank</span>(cs<span class="sc">$</span>dat2<span class="sc">$</span>income), <span class="fu">rank</span>(cs<span class="sc">$</span>dat2<span class="sc">$</span>tax_too_high)) <span class="sc">/</span></span>
<span id="cb321-2"><a href="case-study-pearson-spearman-kendall.html#cb321-2" tabindex="-1"></a>  (<span class="fu">sd</span>(<span class="fu">rank</span>(cs<span class="sc">$</span>dat2<span class="sc">$</span>income)) <span class="sc">*</span> <span class="fu">sd</span>(<span class="fu">rank</span>(cs<span class="sc">$</span>dat2<span class="sc">$</span>tax_too_high)))</span></code></pre></div>
<pre><code>## [1] 0.6024641</code></pre>
<p>Use the function though. I don’t get why <code>cor.test</code> requires <code>x</code> and <code>y</code> be numeric.</p>
<div class="sourceCode" id="cb323"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb323-1"><a href="case-study-pearson-spearman-kendall.html#cb323-1" tabindex="-1"></a>(cs<span class="sc">$</span>spearman <span class="ot">&lt;-</span> </span>
<span id="cb323-2"><a href="case-study-pearson-spearman-kendall.html#cb323-2" tabindex="-1"></a>  <span class="fu">cor.test</span>(</span>
<span id="cb323-3"><a href="case-study-pearson-spearman-kendall.html#cb323-3" tabindex="-1"></a>    <span class="fu">as.numeric</span>(cs<span class="sc">$</span>dat2<span class="sc">$</span>tax_too_high), </span>
<span id="cb323-4"><a href="case-study-pearson-spearman-kendall.html#cb323-4" tabindex="-1"></a>    <span class="fu">as.numeric</span>(cs<span class="sc">$</span>dat2<span class="sc">$</span>income), </span>
<span id="cb323-5"><a href="case-study-pearson-spearman-kendall.html#cb323-5" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>)</span>
<span id="cb323-6"><a href="case-study-pearson-spearman-kendall.html#cb323-6" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Warning in cor.test.default(as.numeric(cs$dat2$tax_too_high),
## as.numeric(cs$dat2$income), : Cannot compute exact p-value with ties</code></pre>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  as.numeric(cs$dat2$tax_too_high) and as.numeric(cs$dat2$income)
## S = 914.33, p-value = 0.001837
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##       rho 
## 0.6024641</code></pre>
<p>Interpret the statistic using the same rule of thumb as for Pearson’s correlation. A rho over .5 is a strong correlation.</p>
<blockquote>
<p>A Spearman’s rank-order correlation was run to assess the relationship between income level and views towards income taxes in 24 participants. Preliminary analysis showed the relationship to be monotonic, as assessed by visual inspection of a scatterplot. There was a statistically significant, strong positive correlation between income level and views towards income taxes, <span class="math inline">\(r_s\)</span> = 0.602, <em>p</em> = 0.002.</p>
</blockquote>
</div>
<div id="kendalls-tau" class="section level5 unnumbered hasAnchor">
<h5>Kendall’s Tau<a href="case-study-pearson-spearman-kendall.html#kendalls-tau" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Recall that Kendall’s tau is a function of concordant (C), discordant (D) and tied (Tx and Ty) pairs of observations. The manual calculation is a little more involved. Here is the function instead.</p>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb326-1"><a href="case-study-pearson-spearman-kendall.html#cb326-1" tabindex="-1"></a>(cs<span class="sc">$</span>kendall <span class="ot">&lt;-</span> </span>
<span id="cb326-2"><a href="case-study-pearson-spearman-kendall.html#cb326-2" tabindex="-1"></a>  <span class="fu">cor.test</span>(</span>
<span id="cb326-3"><a href="case-study-pearson-spearman-kendall.html#cb326-3" tabindex="-1"></a>    <span class="fu">as.numeric</span>(cs<span class="sc">$</span>dat2<span class="sc">$</span>tax_too_high), </span>
<span id="cb326-4"><a href="case-study-pearson-spearman-kendall.html#cb326-4" tabindex="-1"></a>    <span class="fu">as.numeric</span>(cs<span class="sc">$</span>dat2<span class="sc">$</span>income), </span>
<span id="cb326-5"><a href="case-study-pearson-spearman-kendall.html#cb326-5" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">&quot;kendall&quot;</span>)</span>
<span id="cb326-6"><a href="case-study-pearson-spearman-kendall.html#cb326-6" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Warning in cor.test.default(as.numeric(cs$dat2$tax_too_high),
## as.numeric(cs$dat2$income), : Cannot compute exact p-value with ties</code></pre>
<pre><code>## 
##  Kendall&#39;s rank correlation tau
## 
## data:  as.numeric(cs$dat2$tax_too_high) and as.numeric(cs$dat2$income)
## z = 2.9686, p-value = 0.002991
## alternative hypothesis: true tau is not equal to 0
## sample estimates:
##       tau 
## 0.5345225</code></pre>
<p>As with the case study on cholesterol and television, Kendall’s tau was more conservative than Spearman’s rho. <span class="math inline">\(\tau_b\)</span> = 0.535 is still in the “strong” range, though just barely.</p>
<blockquote>
<p>A Kendall’s tau-b correlation was run to assess the relationship between income level and views towards income taxes amongst 24 participants. Preliminary analysis showed the relationship to be monotonic, as assessed by visual inspection of a scatterplot. There was a statistically significant, strong positive correlation between income level and the view that taxes were too high, <span class="math inline">\(\tau_b\)</span> = 0.535, <em>p</em> = 0.003.</p>
</blockquote>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="kendall.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chisq-independence.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="assets/gitbook-2.6.7/js/app.min.js"></script>
<script src="assets/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="assets/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection",
"scroll_highlight": true
},
"toolbar": {
"position": "static"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
