<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3.3 Markov Chain Monte Carlo (MCMC) | Statistical Inference</title>
  <meta name="description" content="Notes cobbled together from books, online classes, etc. to be used as quick reference for common work projects." />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content="3.3 Markov Chain Monte Carlo (MCMC) | Statistical Inference" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Notes cobbled together from books, online classes, etc. to be used as quick reference for common work projects." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3.3 Markov Chain Monte Carlo (MCMC) | Statistical Inference" />
  
  <meta name="twitter:description" content="Notes cobbled together from books, online classes, etc. to be used as quick reference for common work projects." />
  

<meta name="author" content="Michael Foley" />


<meta name="date" content="2023-11-02" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="bayesian-inference.html"/>
<link rel="next" href="gamma-poisson-and-estimating-counts.html"/>
<script src="assets/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="assets/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="assets/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="assets/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="assets/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="assets/tabwid-1.1.3/tabwid.css" rel="stylesheet" />
<script src="assets/tabwid-1.1.3/tabwid.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="frequentist-statistics.html"><a href="frequentist-statistics.html"><i class="fa fa-check"></i><b>1</b> Frequentist Statistics</a>
<ul>
<li class="chapter" data-level="1.1" data-path="central-tendancy-and-dispersion.html"><a href="central-tendancy-and-dispersion.html"><i class="fa fa-check"></i><b>1.1</b> Central Tendancy and Dispersion</a></li>
<li class="chapter" data-level="1.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>1.2</b> Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#type-i-and-ii-errors"><i class="fa fa-check"></i>Type I and II Errors</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#statistical-power"><i class="fa fa-check"></i>Statistical Power</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#what-p-values-would-you-expect"><i class="fa fa-check"></i>What p-values would you expect?</a></li>
<li class="chapter" data-level="1.2.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#further-reading"><i class="fa fa-check"></i><b>1.2.1</b> Further Reading</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="likelihood-statistics.html"><a href="likelihood-statistics.html"><i class="fa fa-check"></i><b>2</b> Likelihood Statistics</a>
<ul>
<li class="chapter" data-level="2.1" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html"><i class="fa fa-check"></i><b>2.1</b> Maximum Likelihood Estimation</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="bayesian-statistics.html"><a href="bayesian-statistics.html"><i class="fa fa-check"></i><b>3</b> Bayesian Statistics</a>
<ul>
<li class="chapter" data-level="3.1" data-path="bayes-theorem.html"><a href="bayes-theorem.html"><i class="fa fa-check"></i><b>3.1</b> Bayes’ Theorem</a></li>
<li class="chapter" data-level="3.2" data-path="bayesian-inference.html"><a href="bayesian-inference.html"><i class="fa fa-check"></i><b>3.2</b> Bayesian Inference</a></li>
<li class="chapter" data-level="3.3" data-path="markov-chain-monte-carlo-mcmc.html"><a href="markov-chain-monte-carlo-mcmc.html"><i class="fa fa-check"></i><b>3.3</b> Markov Chain Monte Carlo (MCMC)</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="markov-chain-monte-carlo-mcmc.html"><a href="markov-chain-monte-carlo-mcmc.html#the-classical-approach"><i class="fa fa-check"></i><b>3.3.1</b> The Classical Approach</a></li>
<li class="chapter" data-level="3.3.2" data-path="markov-chain-monte-carlo-mcmc.html"><a href="markov-chain-monte-carlo-mcmc.html#rejection-sampling"><i class="fa fa-check"></i><b>3.3.2</b> Rejection Sampling</a></li>
<li class="chapter" data-level="3.3.3" data-path="markov-chain-monte-carlo-mcmc.html"><a href="markov-chain-monte-carlo-mcmc.html#gibbs-sampler"><i class="fa fa-check"></i><b>3.3.3</b> Gibbs Sampler</a></li>
<li class="chapter" data-level="3.3.4" data-path="markov-chain-monte-carlo-mcmc.html"><a href="markov-chain-monte-carlo-mcmc.html#metropolis-hastings"><i class="fa fa-check"></i><b>3.3.4</b> Metropolis-Hastings</a></li>
<li class="chapter" data-level="3.3.5" data-path="markov-chain-monte-carlo-mcmc.html"><a href="markov-chain-monte-carlo-mcmc.html#other-notes"><i class="fa fa-check"></i><b>3.3.5</b> Other Notes</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="gamma-poisson-and-estimating-counts.html"><a href="gamma-poisson-and-estimating-counts.html"><i class="fa fa-check"></i><b>3.4</b> Gamma Poisson and Estimating Counts</a></li>
<li class="chapter" data-level="3.5" data-path="normal-and-estimating-means.html"><a href="normal-and-estimating-means.html"><i class="fa fa-check"></i><b>3.5</b> Normal and Estimating Means</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="normal-and-estimating-means.html"><a href="normal-and-estimating-means.html#normal-pop-est"><i class="fa fa-check"></i><b>3.5.1</b> Population Estimate</a></li>
<li class="chapter" data-level="3.5.2" data-path="normal-and-estimating-means.html"><a href="normal-and-estimating-means.html#regression"><i class="fa fa-check"></i><b>3.5.2</b> Regression</a></li>
<li class="chapter" data-level="3.5.3" data-path="normal-and-estimating-means.html"><a href="normal-and-estimating-means.html#generalized-linear-models"><i class="fa fa-check"></i><b>3.5.3</b> Generalized Linear Models</a></li>
<li class="chapter" data-level="3.5.4" data-path="normal-and-estimating-means.html"><a href="normal-and-estimating-means.html#missing-data"><i class="fa fa-check"></i><b>3.5.4</b> Missing Data</a></li>
<li class="chapter" data-level="3.5.5" data-path="normal-and-estimating-means.html"><a href="normal-and-estimating-means.html#change-point-regression"><i class="fa fa-check"></i><b>3.5.5</b> Change Point Regression</a></li>
<li class="chapter" data-level="3.5.6" data-path="normal-and-estimating-means.html"><a href="normal-and-estimating-means.html#cluster-analysis"><i class="fa fa-check"></i><b>3.5.6</b> Cluster Analysis</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="beta-binomial-and-estimating-proportions.html"><a href="beta-binomial-and-estimating-proportions.html"><i class="fa fa-check"></i><b>3.6</b> Beta Binomial and Estimating Proportions</a></li>
<li class="chapter" data-level="3.7" data-path="zero-inflation-and-latent-variables.html"><a href="zero-inflation-and-latent-variables.html"><i class="fa fa-check"></i><b>3.7</b> Zero-Inflation and Latent Variables</a></li>
<li class="chapter" data-level="3.8" data-path="dic.html"><a href="dic.html"><i class="fa fa-check"></i><b>3.8</b> DIC</a></li>
<li class="chapter" data-level="3.9" data-path="monte-carlo-integration.html"><a href="monte-carlo-integration.html"><i class="fa fa-check"></i><b>3.9</b> Monte Carlo Integration</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="monte-carlo-integration.html"><a href="monte-carlo-integration.html#inverse-sampling"><i class="fa fa-check"></i><b>3.9.1</b> Inverse Sampling</a></li>
<li class="chapter" data-level="3.9.2" data-path="monte-carlo-integration.html"><a href="monte-carlo-integration.html#rejection-sampling-1"><i class="fa fa-check"></i><b>3.9.2</b> Rejection Sampling</a></li>
<li class="chapter" data-level="3.9.3" data-path="monte-carlo-integration.html"><a href="monte-carlo-integration.html#importance-sampling"><i class="fa fa-check"></i><b>3.9.3</b> Importance Sampling</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="metropolis-hastings-1.html"><a href="metropolis-hastings-1.html"><i class="fa fa-check"></i><b>3.10</b> Metropolis-Hastings</a></li>
<li class="chapter" data-level="3.11" data-path="mixed-effects-linear-regression.html"><a href="mixed-effects-linear-regression.html"><i class="fa fa-check"></i><b>3.11</b> Mixed Effects Linear Regression</a></li>
<li class="chapter" data-level="3.12" data-path="appendix-bayes-factors.html"><a href="appendix-bayes-factors.html"><i class="fa fa-check"></i><b>3.12</b> Appendix: Bayes Factors</a></li>
<li class="chapter" data-level="3.13" data-path="further-reading-1.html"><a href="further-reading-1.html"><i class="fa fa-check"></i><b>3.13</b> Further Reading</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="one-sample.html"><a href="one-sample.html"><i class="fa fa-check"></i><b>4</b> One-Sample</a>
<ul>
<li class="chapter" data-level="4.1" data-path="one-sample-mean-z-test.html"><a href="one-sample-mean-z-test.html"><i class="fa fa-check"></i><b>4.1</b> One-Sample Mean z Test</a></li>
<li class="chapter" data-level="4.2" data-path="one-sample-mean-t-test.html"><a href="one-sample-mean-t-test.html"><i class="fa fa-check"></i><b>4.2</b> One-Sample Mean t Test</a></li>
<li class="chapter" data-level="4.3" data-path="one-sample-median-wilcoxon-test.html"><a href="one-sample-median-wilcoxon-test.html"><i class="fa fa-check"></i><b>4.3</b> One-Sample Median Wilcoxon Test</a></li>
<li class="chapter" data-level="4.4" data-path="chi-squared-goodness-of-fit-test.html"><a href="chi-squared-goodness-of-fit-test.html"><i class="fa fa-check"></i><b>4.4</b> Chi-Squared Goodness-of-Fit Test</a></li>
<li class="chapter" data-level="4.5" data-path="g-test.html"><a href="g-test.html"><i class="fa fa-check"></i><b>4.5</b> G-Test</a></li>
<li class="chapter" data-level="4.6" data-path="one-sample-poisson-test.html"><a href="one-sample-poisson-test.html"><i class="fa fa-check"></i><b>4.6</b> One-Sample Poisson Test</a></li>
<li class="chapter" data-level="4.7" data-path="exact-binomial-test.html"><a href="exact-binomial-test.html"><i class="fa fa-check"></i><b>4.7</b> Exact Binomial Test</a></li>
<li class="chapter" data-level="4.8" data-path="one-sample-proportion-z-test.html"><a href="one-sample-proportion-z-test.html"><i class="fa fa-check"></i><b>4.8</b> One-Sample Proportion z Test</a></li>
<li class="chapter" data-level="4.9" data-path="sample-t-test-for-categorical-var.html"><a href="sample-t-test-for-categorical-var.html"><i class="fa fa-check"></i><b>4.9</b> 1 sample t Test for Categorical Var</a></li>
<li class="chapter" data-level="4.10" data-path="wilcoxon-1-sample-median-test-for-categorical-var.html"><a href="wilcoxon-1-sample-median-test-for-categorical-var.html"><i class="fa fa-check"></i><b>4.10</b> Wilcoxon 1-Sample Median Test for Categorical Var</a></li>
<li class="chapter" data-level="4.11" data-path="multivariate-statistics.html"><a href="multivariate-statistics.html"><i class="fa fa-check"></i><b>4.11</b> Multivariate Statistics</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="group-differences.html"><a href="group-differences.html"><i class="fa fa-check"></i><b>5</b> Group Differences</a>
<ul>
<li class="chapter" data-level="5.1" data-path="ttest.html"><a href="ttest.html"><i class="fa fa-check"></i><b>5.1</b> Independent Samples t-Test</a></li>
<li class="chapter" data-level="5.2" data-path="wilcoxonranksum.html"><a href="wilcoxonranksum.html"><i class="fa fa-check"></i><b>5.2</b> Wilcoxon Rank Sum Test</a></li>
<li class="chapter" data-level="" data-path="case-study-1.html"><a href="case-study-1.html"><i class="fa fa-check"></i>Case Study 1</a></li>
<li class="chapter" data-level="5.3" data-path="pairedttest.html"><a href="pairedttest.html"><i class="fa fa-check"></i><b>5.3</b> Paired Samples t-Test</a></li>
<li class="chapter" data-level="5.4" data-path="wilcoxonsignedrank.html"><a href="wilcoxonsignedrank.html"><i class="fa fa-check"></i><b>5.4</b> Wilcoxon Signed-Rank Test</a>
<ul>
<li class="chapter" data-level="" data-path="wilcoxonsignedrank.html"><a href="wilcoxonsignedrank.html#sign-test"><i class="fa fa-check"></i>Sign Test</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="case-study-2.html"><a href="case-study-2.html"><i class="fa fa-check"></i>Case Study 2</a></li>
<li class="chapter" data-level="5.5" data-path="onewayanova.html"><a href="onewayanova.html"><i class="fa fa-check"></i><b>5.5</b> One-way ANOVA</a></li>
<li class="chapter" data-level="5.6" data-path="kw.html"><a href="kw.html"><i class="fa fa-check"></i><b>5.6</b> Kruskal–Wallis Test</a></li>
<li class="chapter" data-level="" data-path="groupdiffscs3.html"><a href="groupdiffscs3.html"><i class="fa fa-check"></i>Case Study 3</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="groupdiffscs3.html"><a href="groupdiffscs3.html#assumptions"><i class="fa fa-check"></i><b>5.6.1</b> Assumptions</a></li>
<li class="chapter" data-level="5.6.2" data-path="groupdiffscs3.html"><a href="groupdiffscs3.html#anova"><i class="fa fa-check"></i><b>5.6.2</b> ANOVA</a></li>
<li class="chapter" data-level="5.6.3" data-path="groupdiffscs3.html"><a href="groupdiffscs3.html#kruskal-wallis-test"><i class="fa fa-check"></i><b>5.6.3</b> Kruskal-Wallis Test</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="chisqhomogeneity.html"><a href="chisqhomogeneity.html"><i class="fa fa-check"></i><b>5.7</b> Chi-Square Test of Homogeneity</a></li>
<li class="chapter" data-level="5.8" data-path="fisherexact.html"><a href="fisherexact.html"><i class="fa fa-check"></i><b>5.8</b> Fisher’s Exact Test</a></li>
<li class="chapter" data-level="" data-path="case-study-4.html"><a href="case-study-4.html"><i class="fa fa-check"></i>Case Study 4</a></li>
<li class="chapter" data-level="5.9" data-path="pairwiseproptest.html"><a href="pairwiseproptest.html"><i class="fa fa-check"></i><b>5.9</b> Pairwise Prop Test</a></li>
<li class="chapter" data-level="5.10" data-path="mcnemar.html"><a href="mcnemar.html"><i class="fa fa-check"></i><b>5.10</b> McNemar’s Test</a>
<ul>
<li class="chapter" data-level="5.10.1" data-path="mcnemar.html"><a href="mcnemar.html#manova"><i class="fa fa-check"></i><b>5.10.1</b> MANOVA</a></li>
<li class="chapter" data-level="5.10.2" data-path="mcnemar.html"><a href="mcnemar.html#multiple-variance-comparison-f-test"><i class="fa fa-check"></i><b>5.10.2</b> Multiple Variance Comparison F Test</a></li>
<li class="chapter" data-level="5.10.3" data-path="mcnemar.html"><a href="mcnemar.html#example-5"><i class="fa fa-check"></i><b>5.10.3</b> Example</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="association.html"><a href="association.html"><i class="fa fa-check"></i><b>6</b> Association</a>
<ul>
<li class="chapter" data-level="6.1" data-path="pearson.html"><a href="pearson.html"><i class="fa fa-check"></i><b>6.1</b> Pearson’s Correlation</a></li>
<li class="chapter" data-level="6.2" data-path="spearman.html"><a href="spearman.html"><i class="fa fa-check"></i><b>6.2</b> Spearman’s Rho</a></li>
<li class="chapter" data-level="6.3" data-path="kendall.html"><a href="kendall.html"><i class="fa fa-check"></i><b>6.3</b> Kendal’s Tau</a></li>
<li class="chapter" data-level="6.4" data-path="case-study-pearson-spearman-kendall.html"><a href="case-study-pearson-spearman-kendall.html"><i class="fa fa-check"></i><b>6.4</b> Case Study: Pearson, Spearman, Kendall</a></li>
<li class="chapter" data-level="6.5" data-path="chisq-independence.html"><a href="chisq-independence.html"><i class="fa fa-check"></i><b>6.5</b> Chi-Square Test of Independence</a></li>
<li class="chapter" data-level="6.6" data-path="fisher-exact.html"><a href="fisher-exact.html"><i class="fa fa-check"></i><b>6.6</b> Fisher’s Exact Test</a></li>
<li class="chapter" data-level="6.7" data-path="case-study-chi-square-fisher.html"><a href="case-study-chi-square-fisher.html"><i class="fa fa-check"></i><b>6.7</b> Case Study: Chi-Square, Fisher</a></li>
<li class="chapter" data-level="6.8" data-path="kruskals-lambda.html"><a href="kruskals-lambda.html"><i class="fa fa-check"></i><b>6.8</b> Kruskal’s Lambda</a></li>
<li class="chapter" data-level="6.9" data-path="relative-risk.html"><a href="relative-risk.html"><i class="fa fa-check"></i><b>6.9</b> Relative Risk</a></li>
<li class="chapter" data-level="6.10" data-path="odds-ratio.html"><a href="odds-ratio.html"><i class="fa fa-check"></i><b>6.10</b> Odds Ratio</a></li>
<li class="chapter" data-level="6.11" data-path="partial-correlation.html"><a href="partial-correlation.html"><i class="fa fa-check"></i><b>6.11</b> Partial Correlation</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="matrix-algebra.html"><a href="matrix-algebra.html"><i class="fa fa-check"></i><b>7</b> Matrix Algebra</a>
<ul>
<li class="chapter" data-level="7.1" data-path="central-tendancy-dispersion-and-association.html"><a href="central-tendancy-dispersion-and-association.html"><i class="fa fa-check"></i><b>7.1</b> Central Tendancy, Dispersion, and Association</a></li>
<li class="chapter" data-level="7.2" data-path="linear-transformations.html"><a href="linear-transformations.html"><i class="fa fa-check"></i><b>7.2</b> Linear Transformations</a></li>
<li class="chapter" data-level="7.3" data-path="multivariate-normal-distribution.html"><a href="multivariate-normal-distribution.html"><i class="fa fa-check"></i><b>7.3</b> Multivariate Normal Distribution</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Inference</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="markov-chain-monte-carlo-mcmc" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Markov Chain Monte Carlo (MCMC)<a href="markov-chain-monte-carlo-mcmc.html#markov-chain-monte-carlo-mcmc" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Markov chain Monte Carlo (MCMC) methods are a class of algorithms for random sampling from high-dimensional probability distributions. Whereas Monte Carlo methods draw independent samples from a distribution, MCMC draw samples where the next value is dependent on the prior sample, creating a chain that zeros in on the target. MCMC improves on the less efficient rejection sampling, grid search, etc. methods. An example will show how Bayesian inference works with the less efficient methods, and the more sophisticated MCMC methods.<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a></p>
<p>The Howell data set contains the height (cm) of 165 adult males. Human height has an <span class="math inline">\(\sim N(\mu, \sigma)\)</span> distribution. What is the expected height of an adult male?</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="markov-chain-monte-carlo-mcmc.html#cb1-1" tabindex="-1"></a><span class="co"># downloaded this from </span></span>
<span id="cb1-2"><a href="markov-chain-monte-carlo-mcmc.html#cb1-2" tabindex="-1"></a><span class="co"># https://github.com/rmcelreath/rethinking/blob/master/data/Howell1.csv</span></span>
<span id="cb1-3"><a href="markov-chain-monte-carlo-mcmc.html#cb1-3" tabindex="-1"></a>howell <span class="ot">&lt;-</span> </span>
<span id="cb1-4"><a href="markov-chain-monte-carlo-mcmc.html#cb1-4" tabindex="-1"></a>  <span class="fu">read_delim</span>(<span class="st">&quot;input/Howell1.csv&quot;</span>, <span class="at">delim =</span> <span class="st">&quot;;&quot;</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-5"><a href="markov-chain-monte-carlo-mcmc.html#cb1-5" tabindex="-1"></a>  <span class="fu">filter</span>(age <span class="sc">&gt;=</span> <span class="dv">18</span>, male <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb1-6"><a href="markov-chain-monte-carlo-mcmc.html#cb1-6" tabindex="-1"></a></span>
<span id="cb1-7"><a href="markov-chain-monte-carlo-mcmc.html#cb1-7" tabindex="-1"></a>howell <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> height)) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">geom_qq_line</span>() <span class="sc">+</span></span>
<span id="cb1-8"><a href="markov-chain-monte-carlo-mcmc.html#cb1-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Adult heights are ~normally distributed.&quot;</span>)</span></code></pre></div>
<p><img src="statistics_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<div id="the-classical-approach" class="section level3 hasAnchor" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> The Classical Approach<a href="markov-chain-monte-carlo-mcmc.html#the-classical-approach" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The classical approach is to construct a 95% CI around the mean with a <a href="https://mpfoley73.github.io/statistics/one-sample-mean-t-test.html">one-sample mean <em>t</em> test</a>. The mean height is 160.4 (95% CI, 159.4 to 161.3) with standard deviation 6.0.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="markov-chain-monte-carlo-mcmc.html#cb2-1" tabindex="-1"></a><span class="fu">t.test</span>(howell<span class="sc">$</span>height)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  howell$height
## t = 342.78, df = 164, p-value &lt; 2.2e-16
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  159.4348 161.2822
## sample estimates:
## mean of x 
##  160.3585</code></pre>
</div>
<div id="rejection-sampling" class="section level3 hasAnchor" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> Rejection Sampling<a href="markov-chain-monte-carlo-mcmc.html#rejection-sampling" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Rejection sampling samples the parameter space (<span class="math inline">\(\mu\)</span> and <span class="math inline">\(\tau\)</span>), then conditions on the observed evidence (<span class="math inline">\(\bar{y}\)</span>).</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="markov-chain-monte-carlo-mcmc.html#cb4-1" tabindex="-1"></a>ITER <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">5</span></span>
<span id="cb4-2"><a href="markov-chain-monte-carlo-mcmc.html#cb4-2" tabindex="-1"></a></span>
<span id="cb4-3"><a href="markov-chain-monte-carlo-mcmc.html#cb4-3" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb4-4"><a href="markov-chain-monte-carlo-mcmc.html#cb4-4" tabindex="-1"></a></span>
<span id="cb4-5"><a href="markov-chain-monte-carlo-mcmc.html#cb4-5" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb4-6"><a href="markov-chain-monte-carlo-mcmc.html#cb4-6" tabindex="-1"></a>  <span class="at">mu =</span> <span class="fu">round</span>(<span class="fu">runif</span>(ITER, <span class="dv">150</span>, <span class="dv">170</span>), <span class="dv">1</span>),</span>
<span id="cb4-7"><a href="markov-chain-monte-carlo-mcmc.html#cb4-7" tabindex="-1"></a>  <span class="at">tau =</span> <span class="fu">round</span>(<span class="fu">runif</span>(ITER, .<span class="dv">3</span>, .<span class="dv">6</span>), <span class="dv">2</span>),</span>
<span id="cb4-8"><a href="markov-chain-monte-carlo-mcmc.html#cb4-8" tabindex="-1"></a>  <span class="at">sampled_height =</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(ITER, mu, <span class="dv">1</span><span class="sc">/</span><span class="fu">sqrt</span>(tau)), <span class="dv">1</span>)</span>
<span id="cb4-9"><a href="markov-chain-monte-carlo-mcmc.html#cb4-9" tabindex="-1"></a>)</span>
<span id="cb4-10"><a href="markov-chain-monte-carlo-mcmc.html#cb4-10" tabindex="-1"></a></span>
<span id="cb4-11"><a href="markov-chain-monte-carlo-mcmc.html#cb4-11" tabindex="-1"></a><span class="co"># Condition on observed mean (160.4)</span></span>
<span id="cb4-12"><a href="markov-chain-monte-carlo-mcmc.html#cb4-12" tabindex="-1"></a>observed_mean <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">mean</span>(howell<span class="sc">$</span>height), <span class="dv">1</span>)</span>
<span id="cb4-13"><a href="markov-chain-monte-carlo-mcmc.html#cb4-13" tabindex="-1"></a>dat <span class="sc">%&gt;%</span> </span>
<span id="cb4-14"><a href="markov-chain-monte-carlo-mcmc.html#cb4-14" tabindex="-1"></a>  <span class="fu">filter</span>(sampled_height <span class="sc">==</span> observed_mean) <span class="sc">%&gt;%</span> </span>
<span id="cb4-15"><a href="markov-chain-monte-carlo-mcmc.html#cb4-15" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mu_mean =</span> <span class="fu">mean</span>(mu), <span class="at">mu_025 =</span> <span class="fu">quantile</span>(mu, .<span class="dv">025</span>), <span class="at">mu_975 =</span> <span class="fu">quantile</span>(mu, .<span class="dv">975</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   mu_mean mu_025 mu_975
##     &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1    160.   157.   163.</code></pre>
<p>This is rather inefficient. We generated 100,000 data points, then conditioned on just the 533 that had the observed mean. Plus, we limited ourselves to one-decimal precision for the search. However, the result, 160.4 (95% CI, 157.3 to 163.4) was close to the classical estimate of 160.4 (95% CI, 159.4 to 161.3)</p>
</div>
<div id="gibbs-sampler" class="section level3 hasAnchor" number="3.3.3">
<h3><span class="header-section-number">3.3.3</span> Gibbs Sampler<a href="markov-chain-monte-carlo-mcmc.html#gibbs-sampler" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Section <a href="normal-and-estimating-means.html#normal-pop-est">3.5.1</a> explains that if you have data from a normally distributed population <span class="math inline">\(\sim N(\mu, \sigma)\)</span>, you can use a normal prior for <span class="math inline">\(\mu \sim N(\mu_0, \tau_0)\)</span> where <span class="math inline">\(\tau = 1 / \sigma^2\)</span>, and a gamma prior for <span class="math inline">\(\tau \sim \text{Gamma}(a, b)\)</span>. The posterior distributions are</p>
<p><span class="math display">\[
\begin{align}
\mu|y &amp; \sim N\left( \frac{n \tau \bar{y}}{n \tau + \tau_0}, n \tau + \tau_0 \right) \\
\tau|y &amp; \sim \text{Gamma} \left( a = \frac{n}{2}, b = \frac{1}{2} \sum_i (y_i - \mu)^2 \right)
\end{align}
\]</span></p>
<p>The Gibbs sampler algorithm is to set priors, randomly sample from <code>rnorm()</code> and <code>rgamma()</code> to get posteriors, then make the posteriors the new priors for repeated iterations. After some burn-in period, the posteriors should stabilize. Take the mean and quantiles of the posteriors (minus the burn-in). From prior knowledge, we know average height is <span class="math inline">\(\mu_0 = 175 \pm 10\)</span>. As a rule of thumb, <span class="math inline">\(\pm\)</span> is 2SD, so <span class="math inline">\(\sigma_0 = 5\)</span> and therefore <span class="math inline">\(\tau_0 = 1 / 5^2\)</span>. For gamma, we can use priors <span class="math inline">\(a = .01\)</span> and <span class="math inline">\(b = .01\)</span>.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="markov-chain-monte-carlo-mcmc.html#cb6-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb6-2"><a href="markov-chain-monte-carlo-mcmc.html#cb6-2" tabindex="-1"></a></span>
<span id="cb6-3"><a href="markov-chain-monte-carlo-mcmc.html#cb6-3" tabindex="-1"></a><span class="co"># Iterations</span></span>
<span id="cb6-4"><a href="markov-chain-monte-carlo-mcmc.html#cb6-4" tabindex="-1"></a>ITER <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">3</span></span>
<span id="cb6-5"><a href="markov-chain-monte-carlo-mcmc.html#cb6-5" tabindex="-1"></a></span>
<span id="cb6-6"><a href="markov-chain-monte-carlo-mcmc.html#cb6-6" tabindex="-1"></a><span class="co"># Prior parameter values based on intuition or prior studies.</span></span>
<span id="cb6-7"><a href="markov-chain-monte-carlo-mcmc.html#cb6-7" tabindex="-1"></a>mu_0 <span class="ot">&lt;-</span> <span class="dv">175</span></span>
<span id="cb6-8"><a href="markov-chain-monte-carlo-mcmc.html#cb6-8" tabindex="-1"></a>tau_0 <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> <span class="dv">5</span><span class="sc">^</span><span class="dv">2</span></span>
<span id="cb6-9"><a href="markov-chain-monte-carlo-mcmc.html#cb6-9" tabindex="-1"></a></span>
<span id="cb6-10"><a href="markov-chain-monte-carlo-mcmc.html#cb6-10" tabindex="-1"></a><span class="co"># Monitors to track burn-in.</span></span>
<span id="cb6-11"><a href="markov-chain-monte-carlo-mcmc.html#cb6-11" tabindex="-1"></a>monitor_mu <span class="ot">&lt;-</span> <span class="fu">numeric</span>(ITER)</span>
<span id="cb6-12"><a href="markov-chain-monte-carlo-mcmc.html#cb6-12" tabindex="-1"></a>monitor_tau <span class="ot">&lt;-</span> <span class="fu">numeric</span>(ITER)</span>
<span id="cb6-13"><a href="markov-chain-monte-carlo-mcmc.html#cb6-13" tabindex="-1"></a></span>
<span id="cb6-14"><a href="markov-chain-monte-carlo-mcmc.html#cb6-14" tabindex="-1"></a><span class="co"># Initialize the algorithm.</span></span>
<span id="cb6-15"><a href="markov-chain-monte-carlo-mcmc.html#cb6-15" tabindex="-1"></a>(n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(howell))</span>
<span id="cb6-16"><a href="markov-chain-monte-carlo-mcmc.html#cb6-16" tabindex="-1"></a><span class="do">## [1] 165</span></span>
<span id="cb6-17"><a href="markov-chain-monte-carlo-mcmc.html#cb6-17" tabindex="-1"></a>y <span class="ot">&lt;-</span> howell<span class="sc">$</span>height</span>
<span id="cb6-18"><a href="markov-chain-monte-carlo-mcmc.html#cb6-18" tabindex="-1"></a>(y_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(y))</span>
<span id="cb6-19"><a href="markov-chain-monte-carlo-mcmc.html#cb6-19" tabindex="-1"></a><span class="do">## [1] 160.3585</span></span>
<span id="cb6-20"><a href="markov-chain-monte-carlo-mcmc.html#cb6-20" tabindex="-1"></a>(mu <span class="ot">&lt;-</span> <span class="fu">mean</span>(y))</span>
<span id="cb6-21"><a href="markov-chain-monte-carlo-mcmc.html#cb6-21" tabindex="-1"></a><span class="do">## [1] 160.3585</span></span>
<span id="cb6-22"><a href="markov-chain-monte-carlo-mcmc.html#cb6-22" tabindex="-1"></a>(tau <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> <span class="fu">var</span>(y))</span>
<span id="cb6-23"><a href="markov-chain-monte-carlo-mcmc.html#cb6-23" tabindex="-1"></a><span class="do">## [1] 0.027693</span></span>
<span id="cb6-24"><a href="markov-chain-monte-carlo-mcmc.html#cb6-24" tabindex="-1"></a>a <span class="ot">&lt;-</span> .<span class="dv">01</span></span>
<span id="cb6-25"><a href="markov-chain-monte-carlo-mcmc.html#cb6-25" tabindex="-1"></a>b <span class="ot">&lt;-</span> .<span class="dv">01</span></span>
<span id="cb6-26"><a href="markov-chain-monte-carlo-mcmc.html#cb6-26" tabindex="-1"></a></span>
<span id="cb6-27"><a href="markov-chain-monte-carlo-mcmc.html#cb6-27" tabindex="-1"></a><span class="cf">for</span>(iter <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>ITER) {</span>
<span id="cb6-28"><a href="markov-chain-monte-carlo-mcmc.html#cb6-28" tabindex="-1"></a>  <span class="co"># mu</span></span>
<span id="cb6-29"><a href="markov-chain-monte-carlo-mcmc.html#cb6-29" tabindex="-1"></a>  new_mu <span class="ot">&lt;-</span> (n <span class="sc">*</span> tau <span class="sc">*</span> y_bar) <span class="sc">/</span> (n <span class="sc">*</span> tau <span class="sc">+</span> tau_0)</span>
<span id="cb6-30"><a href="markov-chain-monte-carlo-mcmc.html#cb6-30" tabindex="-1"></a>  new_tau <span class="ot">&lt;-</span> n <span class="sc">*</span> tau <span class="sc">+</span> tau_0</span>
<span id="cb6-31"><a href="markov-chain-monte-carlo-mcmc.html#cb6-31" tabindex="-1"></a>  monitor_mu[iter] <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, new_mu, <span class="dv">1</span> <span class="sc">/</span> <span class="fu">sqrt</span>(new_tau))</span>
<span id="cb6-32"><a href="markov-chain-monte-carlo-mcmc.html#cb6-32" tabindex="-1"></a>  <span class="co"># tau</span></span>
<span id="cb6-33"><a href="markov-chain-monte-carlo-mcmc.html#cb6-33" tabindex="-1"></a>  new_a <span class="ot">&lt;-</span> a <span class="sc">+</span> n<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb6-34"><a href="markov-chain-monte-carlo-mcmc.html#cb6-34" tabindex="-1"></a>  new_b <span class="ot">&lt;-</span> b <span class="sc">+</span> .<span class="dv">5</span> <span class="sc">*</span> <span class="fu">sum</span>((y<span class="sc">-</span>mu)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb6-35"><a href="markov-chain-monte-carlo-mcmc.html#cb6-35" tabindex="-1"></a>  monitor_tau[iter] <span class="ot">&lt;-</span> <span class="fu">rgamma</span>(<span class="dv">1</span>, new_a, new_b)</span>
<span id="cb6-36"><a href="markov-chain-monte-carlo-mcmc.html#cb6-36" tabindex="-1"></a>  <span class="co"># update state</span></span>
<span id="cb6-37"><a href="markov-chain-monte-carlo-mcmc.html#cb6-37" tabindex="-1"></a>  mu <span class="ot">&lt;-</span> monitor_mu[iter]</span>
<span id="cb6-38"><a href="markov-chain-monte-carlo-mcmc.html#cb6-38" tabindex="-1"></a>  tau <span class="ot">&lt;-</span> monitor_tau[iter]</span>
<span id="cb6-39"><a href="markov-chain-monte-carlo-mcmc.html#cb6-39" tabindex="-1"></a>}</span>
<span id="cb6-40"><a href="markov-chain-monte-carlo-mcmc.html#cb6-40" tabindex="-1"></a></span>
<span id="cb6-41"><a href="markov-chain-monte-carlo-mcmc.html#cb6-41" tabindex="-1"></a><span class="co"># Discard burn-in and estimate.</span></span>
<span id="cb6-42"><a href="markov-chain-monte-carlo-mcmc.html#cb6-42" tabindex="-1"></a><span class="fu">mean</span>(monitor_mu[<span class="sc">-</span><span class="dv">500</span>])</span>
<span id="cb6-43"><a href="markov-chain-monte-carlo-mcmc.html#cb6-43" tabindex="-1"></a><span class="do">## [1] 158.9003</span></span>
<span id="cb6-44"><a href="markov-chain-monte-carlo-mcmc.html#cb6-44" tabindex="-1"></a><span class="fu">quantile</span>(monitor_mu[<span class="sc">-</span><span class="dv">500</span>], <span class="fu">c</span>(.<span class="dv">025</span>, .<span class="dv">975</span>))</span>
<span id="cb6-45"><a href="markov-chain-monte-carlo-mcmc.html#cb6-45" tabindex="-1"></a><span class="do">##     2.5%    97.5% </span></span>
<span id="cb6-46"><a href="markov-chain-monte-carlo-mcmc.html#cb6-46" tabindex="-1"></a><span class="do">## 157.8919 159.8737</span></span>
<span id="cb6-47"><a href="markov-chain-monte-carlo-mcmc.html#cb6-47" tabindex="-1"></a></span>
<span id="cb6-48"><a href="markov-chain-monte-carlo-mcmc.html#cb6-48" tabindex="-1"></a><span class="co"># Check out the burn-in. Actually looks like it took 1 iteration.</span></span>
<span id="cb6-49"><a href="markov-chain-monte-carlo-mcmc.html#cb6-49" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">index =</span> <span class="dv">1</span><span class="sc">:</span>ITER, <span class="at">M =</span> monitor_mu) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> index, <span class="at">y =</span> M)) <span class="sc">+</span> <span class="fu">geom_line</span>()</span></code></pre></div>
<p><img src="statistics_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
</div>
<div id="metropolis-hastings" class="section level3 hasAnchor" number="3.3.4">
<h3><span class="header-section-number">3.3.4</span> Metropolis-Hastings<a href="markov-chain-monte-carlo-mcmc.html#metropolis-hastings" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The Metropolis-Hastings model is like MCMC except that the posterior is accepted with probability <span class="math inline">\(\min(R, 1)\)</span> where <span class="math inline">\(R\)</span> is</p>
<p><span class="math display">\[
R = \frac{f(y|\theta&#39;)f(\theta&#39;)}{f(y|\theta)f(\theta)} \frac{q(\theta|\theta&#39;)}{q(\theta&#39;|\theta)}
\]</span></p>
<p>If the proposed distribution is symmetric, the second term drops out and <span class="math inline">\(R\)</span> is just the ratio of posterior distributions. The symmetric version is called <em>Metropolis</em> instead of <em>Metropolis-Hastings</em>.</p>
<p>Suppose your data is <span class="math inline">\(n = 100\)</span> values from a <span class="math inline">\(N(\mu = 2, \tau = 1/4)\)</span> distribution.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="markov-chain-monte-carlo-mcmc.html#cb7-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb7-2"><a href="markov-chain-monte-carlo-mcmc.html#cb7-2" tabindex="-1"></a></span>
<span id="cb7-3"><a href="markov-chain-monte-carlo-mcmc.html#cb7-3" tabindex="-1"></a><span class="co"># Iterations</span></span>
<span id="cb7-4"><a href="markov-chain-monte-carlo-mcmc.html#cb7-4" tabindex="-1"></a>ITER <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">3</span></span>
<span id="cb7-5"><a href="markov-chain-monte-carlo-mcmc.html#cb7-5" tabindex="-1"></a></span>
<span id="cb7-6"><a href="markov-chain-monte-carlo-mcmc.html#cb7-6" tabindex="-1"></a><span class="co"># Prior parameter values based on intuition or prior studies.</span></span>
<span id="cb7-7"><a href="markov-chain-monte-carlo-mcmc.html#cb7-7" tabindex="-1"></a>mu_0 <span class="ot">&lt;-</span> <span class="dv">175</span></span>
<span id="cb7-8"><a href="markov-chain-monte-carlo-mcmc.html#cb7-8" tabindex="-1"></a>tau_0 <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> <span class="dv">5</span><span class="sc">^</span><span class="dv">2</span></span>
<span id="cb7-9"><a href="markov-chain-monte-carlo-mcmc.html#cb7-9" tabindex="-1"></a></span>
<span id="cb7-10"><a href="markov-chain-monte-carlo-mcmc.html#cb7-10" tabindex="-1"></a><span class="co"># Monitors to track burn-in.</span></span>
<span id="cb7-11"><a href="markov-chain-monte-carlo-mcmc.html#cb7-11" tabindex="-1"></a>monitor_mu <span class="ot">&lt;-</span> <span class="fu">numeric</span>(ITER)</span>
<span id="cb7-12"><a href="markov-chain-monte-carlo-mcmc.html#cb7-12" tabindex="-1"></a>monitor_tau <span class="ot">&lt;-</span> <span class="fu">numeric</span>(ITER)</span>
<span id="cb7-13"><a href="markov-chain-monte-carlo-mcmc.html#cb7-13" tabindex="-1"></a></span>
<span id="cb7-14"><a href="markov-chain-monte-carlo-mcmc.html#cb7-14" tabindex="-1"></a><span class="co"># Initialize the algorithm.</span></span>
<span id="cb7-15"><a href="markov-chain-monte-carlo-mcmc.html#cb7-15" tabindex="-1"></a>(n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(howell))</span></code></pre></div>
<pre><code>## [1] 165</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="markov-chain-monte-carlo-mcmc.html#cb9-1" tabindex="-1"></a>y <span class="ot">&lt;-</span> howell<span class="sc">$</span>height</span>
<span id="cb9-2"><a href="markov-chain-monte-carlo-mcmc.html#cb9-2" tabindex="-1"></a>(y_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(y))</span></code></pre></div>
<pre><code>## [1] 160.3585</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="markov-chain-monte-carlo-mcmc.html#cb11-1" tabindex="-1"></a>(mu <span class="ot">&lt;-</span> <span class="fu">mean</span>(y))</span></code></pre></div>
<pre><code>## [1] 160.3585</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="markov-chain-monte-carlo-mcmc.html#cb13-1" tabindex="-1"></a>(tau <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> <span class="fu">var</span>(y))</span></code></pre></div>
<pre><code>## [1] 0.027693</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="markov-chain-monte-carlo-mcmc.html#cb15-1" tabindex="-1"></a>a <span class="ot">&lt;-</span> .<span class="dv">01</span></span>
<span id="cb15-2"><a href="markov-chain-monte-carlo-mcmc.html#cb15-2" tabindex="-1"></a>b <span class="ot">&lt;-</span> .<span class="dv">01</span></span>
<span id="cb15-3"><a href="markov-chain-monte-carlo-mcmc.html#cb15-3" tabindex="-1"></a></span>
<span id="cb15-4"><a href="markov-chain-monte-carlo-mcmc.html#cb15-4" tabindex="-1"></a><span class="cf">for</span>(iter <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>ITER) {</span>
<span id="cb15-5"><a href="markov-chain-monte-carlo-mcmc.html#cb15-5" tabindex="-1"></a>  <span class="co"># mu</span></span>
<span id="cb15-6"><a href="markov-chain-monte-carlo-mcmc.html#cb15-6" tabindex="-1"></a>  new_mu <span class="ot">&lt;-</span> (n <span class="sc">*</span> tau <span class="sc">*</span> y_bar) <span class="sc">/</span> (n <span class="sc">*</span> tau <span class="sc">+</span> tau_0)</span>
<span id="cb15-7"><a href="markov-chain-monte-carlo-mcmc.html#cb15-7" tabindex="-1"></a>  new_tau <span class="ot">&lt;-</span> n <span class="sc">*</span> tau <span class="sc">+</span> tau_0</span>
<span id="cb15-8"><a href="markov-chain-monte-carlo-mcmc.html#cb15-8" tabindex="-1"></a>  proposed_mu <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, new_mu, <span class="dv">1</span> <span class="sc">/</span> <span class="fu">sqrt</span>(new_tau)) <span class="co"># tentative for now!</span></span>
<span id="cb15-9"><a href="markov-chain-monte-carlo-mcmc.html#cb15-9" tabindex="-1"></a>  <span class="co"># tau</span></span>
<span id="cb15-10"><a href="markov-chain-monte-carlo-mcmc.html#cb15-10" tabindex="-1"></a>  new_a <span class="ot">&lt;-</span> a <span class="sc">+</span> n<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb15-11"><a href="markov-chain-monte-carlo-mcmc.html#cb15-11" tabindex="-1"></a>  new_b <span class="ot">&lt;-</span> b <span class="sc">+</span> .<span class="dv">5</span> <span class="sc">*</span> <span class="fu">sum</span>((y<span class="sc">-</span>mu)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb15-12"><a href="markov-chain-monte-carlo-mcmc.html#cb15-12" tabindex="-1"></a>  monitor_tau[iter] <span class="ot">&lt;-</span> <span class="fu">rgamma</span>(<span class="dv">1</span>, new_a, new_b)</span>
<span id="cb15-13"><a href="markov-chain-monte-carlo-mcmc.html#cb15-13" tabindex="-1"></a>  <span class="co"># update state</span></span>
<span id="cb15-14"><a href="markov-chain-monte-carlo-mcmc.html#cb15-14" tabindex="-1"></a>  <span class="co"># log of the acceptance ratio</span></span>
<span id="cb15-15"><a href="markov-chain-monte-carlo-mcmc.html#cb15-15" tabindex="-1"></a>  logR <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">dnorm</span>(y, proposed_mu, <span class="dv">1</span><span class="sc">/</span><span class="fu">sqrt</span>(tau), <span class="at">log =</span> T)) <span class="sc">-</span> <span class="co"># new likelihood</span></span>
<span id="cb15-16"><a href="markov-chain-monte-carlo-mcmc.html#cb15-16" tabindex="-1"></a>          <span class="fu">sum</span>(<span class="fu">dnorm</span>(y, mu         , <span class="dv">1</span><span class="sc">/</span><span class="fu">sqrt</span>(tau), <span class="at">log =</span> T)) <span class="sc">+</span> <span class="co"># old likelihood</span></span>
<span id="cb15-17"><a href="markov-chain-monte-carlo-mcmc.html#cb15-17" tabindex="-1"></a>          <span class="fu">dnorm</span>(proposed_mu, mu_0, <span class="dv">1</span><span class="sc">/</span><span class="fu">sqrt</span>(tau_0), <span class="at">log =</span> T) <span class="sc">-</span> <span class="co"># new prior</span></span>
<span id="cb15-18"><a href="markov-chain-monte-carlo-mcmc.html#cb15-18" tabindex="-1"></a>          <span class="fu">dnorm</span>(mu         , mu_0, <span class="dv">1</span><span class="sc">/</span><span class="fu">sqrt</span>(tau_0), <span class="at">log =</span> T)   <span class="co"># old prior</span></span>
<span id="cb15-19"><a href="markov-chain-monte-carlo-mcmc.html#cb15-19" tabindex="-1"></a>  <span class="co"># accept with probability min(R,1)</span></span>
<span id="cb15-20"><a href="markov-chain-monte-carlo-mcmc.html#cb15-20" tabindex="-1"></a>  logU <span class="ot">&lt;-</span> <span class="fu">log</span>(<span class="fu">runif</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb15-21"><a href="markov-chain-monte-carlo-mcmc.html#cb15-21" tabindex="-1"></a>  <span class="cf">if</span>(logU <span class="sc">&lt;</span> logR) {mu <span class="ot">&lt;-</span> new_mu}</span>
<span id="cb15-22"><a href="markov-chain-monte-carlo-mcmc.html#cb15-22" tabindex="-1"></a>  monitor_mu[iter] <span class="ot">&lt;-</span> mu <span class="co"># this is either current or the proposed.</span></span>
<span id="cb15-23"><a href="markov-chain-monte-carlo-mcmc.html#cb15-23" tabindex="-1"></a>  tau <span class="ot">&lt;-</span> monitor_tau[iter]</span>
<span id="cb15-24"><a href="markov-chain-monte-carlo-mcmc.html#cb15-24" tabindex="-1"></a>}</span>
<span id="cb15-25"><a href="markov-chain-monte-carlo-mcmc.html#cb15-25" tabindex="-1"></a></span>
<span id="cb15-26"><a href="markov-chain-monte-carlo-mcmc.html#cb15-26" tabindex="-1"></a><span class="co"># Discard burn-in and estimate.</span></span>
<span id="cb15-27"><a href="markov-chain-monte-carlo-mcmc.html#cb15-27" tabindex="-1"></a><span class="fu">mean</span>(monitor_mu[<span class="sc">-</span><span class="dv">500</span>])</span></code></pre></div>
<pre><code>## [1] 158.9385</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="markov-chain-monte-carlo-mcmc.html#cb17-1" tabindex="-1"></a><span class="fu">quantile</span>(monitor_mu[<span class="sc">-</span><span class="dv">500</span>], <span class="fu">c</span>(.<span class="dv">025</span>, .<span class="dv">975</span>))</span></code></pre></div>
<pre><code>##     2.5%    97.5% 
## 158.5900 159.2169</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="markov-chain-monte-carlo-mcmc.html#cb19-1" tabindex="-1"></a><span class="co"># Check out the burn-in. Actually looks like it took 1 iteration.</span></span>
<span id="cb19-2"><a href="markov-chain-monte-carlo-mcmc.html#cb19-2" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">index =</span> <span class="dv">1</span><span class="sc">:</span>ITER, <span class="at">M =</span> monitor_mu) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> index, <span class="at">y =</span> M)) <span class="sc">+</span> <span class="fu">geom_line</span>()</span></code></pre></div>
<p><img src="statistics_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
</div>
<div id="other-notes" class="section level3 hasAnchor" number="3.3.5">
<h3><span class="header-section-number">3.3.5</span> Other Notes<a href="markov-chain-monte-carlo-mcmc.html#other-notes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>One simple Bayesian approach is to run several (we’ll use 1,000) experiments that sample 100 ad impression events from an <code>rbinom()</code> generative model using a uniform prior distribution of 0-30% click probability. The resulting 1,000 row data set of click probabilities is the prior predictive distribution of <span class="math inline">\(D\)</span>, the denominator of Bayes’ Theorem. The subset where <span class="math inline">\(D = 13\)</span> is the likelihood, <span class="math inline">\(P(D|\theta)\)</span>. The sampled <span class="math inline">\(\theta\)</span>’s are the prior, <span class="math inline">\(P(\theta) = \text{unif}(.0, .3)\)</span>. Their product is the joint probability distribution, <span class="math inline">\(P(D|\theta)P(\theta)\)</span>, the numerator of Bayes’ Theorem. This method is called <em>rejection sampling</em> because you sample across the whole parameter space, then condition on the observed evidence.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="markov-chain-monte-carlo-mcmc.html#cb20-1" tabindex="-1"></a>df_sim <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb20-2"><a href="markov-chain-monte-carlo-mcmc.html#cb20-2" tabindex="-1"></a>  <span class="at">click_prob =</span> <span class="fu">runif</span>(<span class="dv">1000</span>, <span class="fl">0.0</span>, <span class="fl">0.3</span>),</span>
<span id="cb20-3"><a href="markov-chain-monte-carlo-mcmc.html#cb20-3" tabindex="-1"></a>  <span class="at">click_n =</span> <span class="fu">rbinom</span>(<span class="dv">1000</span>, <span class="dv">100</span>, click_prob)</span>
<span id="cb20-4"><a href="markov-chain-monte-carlo-mcmc.html#cb20-4" tabindex="-1"></a>)</span>
<span id="cb20-5"><a href="markov-chain-monte-carlo-mcmc.html#cb20-5" tabindex="-1"></a></span>
<span id="cb20-6"><a href="markov-chain-monte-carlo-mcmc.html#cb20-6" tabindex="-1"></a>df_sim <span class="sc">%&gt;%</span> </span>
<span id="cb20-7"><a href="markov-chain-monte-carlo-mcmc.html#cb20-7" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">is_13 =</span> <span class="fu">factor</span>(click_n <span class="sc">==</span> <span class="dv">13</span>, <span class="at">levels =</span> <span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">FALSE</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb20-8"><a href="markov-chain-monte-carlo-mcmc.html#cb20-8" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> click_prob, <span class="at">y =</span> click_n, <span class="at">color =</span> is_13)) <span class="sc">+</span></span>
<span id="cb20-9"><a href="markov-chain-monte-carlo-mcmc.html#cb20-9" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb20-10"><a href="markov-chain-monte-carlo-mcmc.html#cb20-10" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">13</span>, <span class="at">color =</span> <span class="st">&quot;steelblue&quot;</span>, <span class="at">linetype =</span> <span class="dv">1</span>, <span class="at">linewidth =</span> .<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb20-11"><a href="markov-chain-monte-carlo-mcmc.html#cb20-11" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;TRUE&quot;</span> <span class="ot">=</span> <span class="st">&quot;steelblue&quot;</span>, <span class="st">&quot;FALSE&quot;</span> <span class="ot">=</span> <span class="st">&quot;gray80&quot;</span>)) <span class="sc">+</span></span>
<span id="cb20-12"><a href="markov-chain-monte-carlo-mcmc.html#cb20-12" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">40</span>, <span class="dv">10</span>), <span class="dv">13</span>)) <span class="sc">+</span></span>
<span id="cb20-13"><a href="markov-chain-monte-carlo-mcmc.html#cb20-13" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Joint probability of observed clicks and click probability&quot;</span>,</span>
<span id="cb20-14"><a href="markov-chain-monte-carlo-mcmc.html#cb20-14" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;with conditioning on 13 observed clicks.&quot;</span>,</span>
<span id="cb20-15"><a href="markov-chain-monte-carlo-mcmc.html#cb20-15" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;clicks per 100 ads&quot;</span>,</span>
<span id="cb20-16"><a href="markov-chain-monte-carlo-mcmc.html#cb20-16" tabindex="-1"></a>       <span class="at">x =</span> <span class="fu">expression</span>(theta))</span></code></pre></div>
<p><img src="statistics_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Condition the joint probability distribution on the 30 rows that produced 13 observed clicks to update the prior. The <code>quantile()</code> function returns the median and the .025 and .975 percentile values - the <em>credible interval</em>.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="markov-chain-monte-carlo-mcmc.html#cb21-1" tabindex="-1"></a><span class="co"># median and credible interval</span></span>
<span id="cb21-2"><a href="markov-chain-monte-carlo-mcmc.html#cb21-2" tabindex="-1"></a>(sim_ci <span class="ot">&lt;-</span> df_sim <span class="sc">%&gt;%</span> <span class="fu">filter</span>(click_n <span class="sc">==</span> <span class="dv">13</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(click_prob) <span class="sc">%&gt;%</span> </span>
<span id="cb21-3"><a href="markov-chain-monte-carlo-mcmc.html#cb21-3" tabindex="-1"></a>  <span class="fu">quantile</span>(<span class="fu">c</span>(.<span class="dv">025</span>, .<span class="dv">5</span>, .<span class="dv">975</span>)))</span></code></pre></div>
<pre><code>##      2.5%       50%     97.5% 
## 0.1030532 0.1428307 0.2028469</code></pre>
<p>The posterior click rate likelihood is 14.3% with 95% credible interval (10.3%, 20.3%). Here is the density plot of the 30 simulations that produced the 13 clicks. The median and 95% credible interval are marked.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="markov-chain-monte-carlo-mcmc.html#cb23-1" tabindex="-1"></a>df_sim <span class="sc">%&gt;%</span> </span>
<span id="cb23-2"><a href="markov-chain-monte-carlo-mcmc.html#cb23-2" tabindex="-1"></a>  <span class="fu">filter</span>(click_n <span class="sc">==</span> <span class="dv">13</span>) <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="markov-chain-monte-carlo-mcmc.html#cb23-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> click_prob)) <span class="sc">+</span></span>
<span id="cb23-4"><a href="markov-chain-monte-carlo-mcmc.html#cb23-4" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb23-5"><a href="markov-chain-monte-carlo-mcmc.html#cb23-5" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> sim_ci[<span class="dv">2</span>]) <span class="sc">+</span></span>
<span id="cb23-6"><a href="markov-chain-monte-carlo-mcmc.html#cb23-6" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> sim_ci[<span class="dv">1</span>], <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb23-7"><a href="markov-chain-monte-carlo-mcmc.html#cb23-7" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> sim_ci[<span class="dv">3</span>], <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb23-8"><a href="markov-chain-monte-carlo-mcmc.html#cb23-8" tabindex="-1"></a>  <span class="co"># coord_cartesian(xlim = c(0, .3)) +</span></span>
<span id="cb23-9"><a href="markov-chain-monte-carlo-mcmc.html#cb23-9" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="fu">seq</span>(<span class="dv">0</span>, .<span class="dv">3</span>, .<span class="dv">05</span>), sim_ci), <span class="at">labels =</span> <span class="fu">percent_format</span>(.<span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb23-10"><a href="markov-chain-monte-carlo-mcmc.html#cb23-10" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Posterior click likelihood distribution&quot;</span>, </span>
<span id="cb23-11"><a href="markov-chain-monte-carlo-mcmc.html#cb23-11" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="fu">glue</span>(<span class="st">&quot;p = {percent(sim_ci[2], .1)}, 95%-CI (&quot;</span>,</span>
<span id="cb23-12"><a href="markov-chain-monte-carlo-mcmc.html#cb23-12" tabindex="-1"></a>       <span class="st">&quot;{percent(sim_ci[1], .1)}, {percent(sim_ci[3], .1)})&quot;</span>),</span>
<span id="cb23-13"><a href="markov-chain-monte-carlo-mcmc.html#cb23-13" tabindex="-1"></a>       <span class="at">x =</span> <span class="fu">expression</span>(theta), <span class="at">y =</span> <span class="st">&quot;density (likelihood)&quot;</span>)</span></code></pre></div>
<p><img src="statistics_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>That’s pretty close to the classical result! Instead of sampling, you could define a discrete set of candidate click probabilities and calculate the click probability density for the 100 ad impressions. This method is called <em>grid approximation</em>.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="markov-chain-monte-carlo-mcmc.html#cb24-1" tabindex="-1"></a>df_bayes <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(</span>
<span id="cb24-2"><a href="markov-chain-monte-carlo-mcmc.html#cb24-2" tabindex="-1"></a>  <span class="at">click_prob =</span> <span class="fu">seq</span>(<span class="fl">0.01</span>, .<span class="dv">30</span>, <span class="at">by =</span> .<span class="dv">001</span>), </span>
<span id="cb24-3"><a href="markov-chain-monte-carlo-mcmc.html#cb24-3" tabindex="-1"></a>  <span class="at">click_n =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">100</span></span>
<span id="cb24-4"><a href="markov-chain-monte-carlo-mcmc.html#cb24-4" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb24-5"><a href="markov-chain-monte-carlo-mcmc.html#cb24-5" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb24-6"><a href="markov-chain-monte-carlo-mcmc.html#cb24-6" tabindex="-1"></a>    <span class="at">prior =</span> <span class="fu">dunif</span>(click_prob, <span class="at">min =</span> <span class="dv">0</span>, <span class="at">max =</span> <span class="fl">0.3</span>),</span>
<span id="cb24-7"><a href="markov-chain-monte-carlo-mcmc.html#cb24-7" tabindex="-1"></a>    <span class="at">likelihood =</span> <span class="fu">dbinom</span>(click_n, <span class="dv">100</span>, click_prob),</span>
<span id="cb24-8"><a href="markov-chain-monte-carlo-mcmc.html#cb24-8" tabindex="-1"></a>    <span class="at">probability =</span> likelihood <span class="sc">*</span> prior <span class="sc">/</span> <span class="fu">sum</span>(likelihood <span class="sc">*</span> prior)</span>
<span id="cb24-9"><a href="markov-chain-monte-carlo-mcmc.html#cb24-9" tabindex="-1"></a>  )</span>
<span id="cb24-10"><a href="markov-chain-monte-carlo-mcmc.html#cb24-10" tabindex="-1"></a></span>
<span id="cb24-11"><a href="markov-chain-monte-carlo-mcmc.html#cb24-11" tabindex="-1"></a>df_bayes <span class="sc">%&gt;%</span> </span>
<span id="cb24-12"><a href="markov-chain-monte-carlo-mcmc.html#cb24-12" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">is_13 =</span> <span class="fu">factor</span>(click_n <span class="sc">==</span> <span class="dv">13</span>, <span class="at">levels =</span> <span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">FALSE</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb24-13"><a href="markov-chain-monte-carlo-mcmc.html#cb24-13" tabindex="-1"></a>  <span class="co"># filter(probability &gt; .0001) %&gt;%</span></span>
<span id="cb24-14"><a href="markov-chain-monte-carlo-mcmc.html#cb24-14" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> click_prob, <span class="at">y =</span> click_n, <span class="at">color =</span> is_13)) <span class="sc">+</span></span>
<span id="cb24-15"><a href="markov-chain-monte-carlo-mcmc.html#cb24-15" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> probability), <span class="at">show.legend =</span> <span class="cn">FALSE</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb24-16"><a href="markov-chain-monte-carlo-mcmc.html#cb24-16" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">13</span>, <span class="at">color =</span> <span class="st">&quot;steelblue&quot;</span>, <span class="at">linetype =</span> <span class="dv">1</span>, <span class="at">linewidth =</span> .<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb24-17"><a href="markov-chain-monte-carlo-mcmc.html#cb24-17" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">50</span>)) <span class="sc">+</span></span>
<span id="cb24-18"><a href="markov-chain-monte-carlo-mcmc.html#cb24-18" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">50</span>, <span class="dv">10</span>), <span class="dv">13</span>)) <span class="sc">+</span></span>
<span id="cb24-19"><a href="markov-chain-monte-carlo-mcmc.html#cb24-19" tabindex="-1"></a>  <span class="fu">scale_color_gradient</span>(<span class="at">low =</span> <span class="st">&quot;#FFFFFF&quot;</span>, <span class="at">high =</span> <span class="st">&quot;steelblue&quot;</span>) <span class="sc">+</span></span>
<span id="cb24-20"><a href="markov-chain-monte-carlo-mcmc.html#cb24-20" tabindex="-1"></a>  <span class="co"># scale_color_manual(values = c(&quot;TRUE&quot; = &quot;steelblue&quot;, &quot;FALSE&quot; = &quot;gray20&quot;)) +</span></span>
<span id="cb24-21"><a href="markov-chain-monte-carlo-mcmc.html#cb24-21" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Joint probability of clicks and click probability.&quot;</span>,</span>
<span id="cb24-22"><a href="markov-chain-monte-carlo-mcmc.html#cb24-22" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;with conditioning on 13 observed clicks.&quot;</span>,</span>
<span id="cb24-23"><a href="markov-chain-monte-carlo-mcmc.html#cb24-23" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;clicks per 100 ads&quot;</span>,</span>
<span id="cb24-24"><a href="markov-chain-monte-carlo-mcmc.html#cb24-24" tabindex="-1"></a>       <span class="at">x =</span> <span class="fu">expression</span>(theta))</span></code></pre></div>
<p><img src="statistics_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Condition the joint probability distribution on the 13 observed clicks to update your prior. Resample the posterior probability to create a distribution.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="markov-chain-monte-carlo-mcmc.html#cb25-1" tabindex="-1"></a>df_bayes_13 <span class="ot">&lt;-</span> df_bayes <span class="sc">%&gt;%</span> <span class="fu">filter</span>(click_n <span class="sc">==</span> <span class="dv">13</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="markov-chain-monte-carlo-mcmc.html#cb25-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">posterior =</span> probability <span class="sc">/</span> <span class="fu">sum</span>(probability))</span>
<span id="cb25-3"><a href="markov-chain-monte-carlo-mcmc.html#cb25-3" tabindex="-1"></a></span>
<span id="cb25-4"><a href="markov-chain-monte-carlo-mcmc.html#cb25-4" tabindex="-1"></a>sampling_idx <span class="ot">&lt;-</span> <span class="fu">sample</span>(</span>
<span id="cb25-5"><a href="markov-chain-monte-carlo-mcmc.html#cb25-5" tabindex="-1"></a>  <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(df_bayes_13), </span>
<span id="cb25-6"><a href="markov-chain-monte-carlo-mcmc.html#cb25-6" tabindex="-1"></a>  <span class="at">size =</span> <span class="dv">10000</span>, </span>
<span id="cb25-7"><a href="markov-chain-monte-carlo-mcmc.html#cb25-7" tabindex="-1"></a>  <span class="at">replace =</span> <span class="cn">TRUE</span>, </span>
<span id="cb25-8"><a href="markov-chain-monte-carlo-mcmc.html#cb25-8" tabindex="-1"></a>  <span class="at">prob =</span> df_bayes_13<span class="sc">$</span>posterior</span>
<span id="cb25-9"><a href="markov-chain-monte-carlo-mcmc.html#cb25-9" tabindex="-1"></a>)</span>
<span id="cb25-10"><a href="markov-chain-monte-carlo-mcmc.html#cb25-10" tabindex="-1"></a></span>
<span id="cb25-11"><a href="markov-chain-monte-carlo-mcmc.html#cb25-11" tabindex="-1"></a>sampling_vals <span class="ot">&lt;-</span> df_bayes_13[sampling_idx, ]</span>
<span id="cb25-12"><a href="markov-chain-monte-carlo-mcmc.html#cb25-12" tabindex="-1"></a></span>
<span id="cb25-13"><a href="markov-chain-monte-carlo-mcmc.html#cb25-13" tabindex="-1"></a>(df_bayes_ci <span class="ot">&lt;-</span> <span class="fu">quantile</span>(sampling_vals<span class="sc">$</span>click_prob, <span class="fu">c</span>(.<span class="dv">025</span>, .<span class="dv">5</span>, .<span class="dv">975</span>)))</span></code></pre></div>
<pre><code>##  2.5%   50% 97.5% 
## 0.079 0.135 0.212</code></pre>
<p><img src="statistics_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>You can use a Bayesian model to estimate multiple parameters. Suppose you want to predict the water temperature in a lake on Jun 1 based on 5 years of prior water temperatures.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="markov-chain-monte-carlo-mcmc.html#cb27-1" tabindex="-1"></a>temp <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">19</span>, <span class="dv">23</span>, <span class="dv">20</span>, <span class="dv">17</span>, <span class="dv">23</span>)</span></code></pre></div>
<p>You model the water temperature as a normal distribution, <span class="math inline">\(\mathrm{N}(\mu, \sigma^2)\)</span> with a prior distribution <span class="math inline">\(\mu = \mathrm{N}(18, 5^2)\)</span> and <span class="math inline">\(\sigma = \mathrm{unif}(0, 10)\)</span> based on past experience.</p>
<p>Using the grid approximation approach, construct a grid of candidate <span class="math inline">\(\mu\)</span> values from 8 to 30 degrees incremented by .5 degrees, and candidate <span class="math inline">\(\sigma\)</span> values from .1 to 10 incremented by .1 - a 4,500 row data frame.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="markov-chain-monte-carlo-mcmc.html#cb28-1" tabindex="-1"></a>mdl_grid <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(<span class="at">mu =</span> <span class="fu">seq</span>(<span class="dv">8</span>, <span class="dv">30</span>, <span class="at">by =</span> <span class="fl">0.5</span>),</span>
<span id="cb28-2"><a href="markov-chain-monte-carlo-mcmc.html#cb28-2" tabindex="-1"></a>                        <span class="at">sigma =</span> <span class="fu">seq</span>(.<span class="dv">1</span>, <span class="dv">10</span>, <span class="at">by =</span> <span class="fl">0.1</span>))</span></code></pre></div>
<p>For each combination of <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span>, the <em>prior</em> probabilities are the densities from <span class="math inline">\(\mu = \mathrm{N}(18, 5^2)\)</span> and <span class="math inline">\(\sigma = \mathrm{unif}(0, 10)\)</span>. The combined prior is their product. The <em>likelihoods</em> are the products of the probabilities of observing each <code>temp</code> given the candidate <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span> values.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="markov-chain-monte-carlo-mcmc.html#cb29-1" tabindex="-1"></a>mdl_grid_2 <span class="ot">&lt;-</span> mdl_grid <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="markov-chain-monte-carlo-mcmc.html#cb29-2" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb29-3"><a href="markov-chain-monte-carlo-mcmc.html#cb29-3" tabindex="-1"></a>    <span class="at">mu_prior =</span> <span class="fu">map_dbl</span>(mu, <span class="sc">~</span><span class="fu">dnorm</span>(., <span class="at">mean =</span> <span class="dv">18</span>, <span class="at">sd =</span> <span class="dv">5</span>)),</span>
<span id="cb29-4"><a href="markov-chain-monte-carlo-mcmc.html#cb29-4" tabindex="-1"></a>    <span class="at">sigma_prior =</span> <span class="fu">map_dbl</span>(sigma, <span class="sc">~</span><span class="fu">dunif</span>(., <span class="dv">0</span>, <span class="dv">10</span>)),</span>
<span id="cb29-5"><a href="markov-chain-monte-carlo-mcmc.html#cb29-5" tabindex="-1"></a>    <span class="at">prior =</span> mu_prior <span class="sc">*</span> sigma_prior, <span class="co"># combined prior,</span></span>
<span id="cb29-6"><a href="markov-chain-monte-carlo-mcmc.html#cb29-6" tabindex="-1"></a>    <span class="at">likelihood =</span> <span class="fu">map2_dbl</span>(mu, sigma, <span class="sc">~</span><span class="fu">dnorm</span>(temp, .x, .y) <span class="sc">%&gt;%</span> <span class="fu">prod</span>()),</span>
<span id="cb29-7"><a href="markov-chain-monte-carlo-mcmc.html#cb29-7" tabindex="-1"></a>    <span class="at">posterior =</span> likelihood <span class="sc">*</span> prior <span class="sc">/</span> <span class="fu">sum</span>(likelihood <span class="sc">*</span> prior)</span>
<span id="cb29-8"><a href="markov-chain-monte-carlo-mcmc.html#cb29-8" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="statistics_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>Calculate a credible interval by drawing 10,000 samples from the grid with sampling probability equal to the calculated posterior probabilities. Use the <code>quantile()</code> function to estimate the median and .025 and .975 quantile values.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="markov-chain-monte-carlo-mcmc.html#cb30-1" tabindex="-1"></a>sampling_idx <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(mdl_grid), <span class="at">size =</span> <span class="dv">10000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> mdl_grid<span class="sc">$</span>posterior)</span></code></pre></div>
<pre><code>## Warning: Unknown or uninitialised column: `posterior`.</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="markov-chain-monte-carlo-mcmc.html#cb32-1" tabindex="-1"></a>sampling_vals <span class="ot">&lt;-</span> mdl_grid[sampling_idx, <span class="fu">c</span>(<span class="st">&quot;mu&quot;</span>, <span class="st">&quot;sigma&quot;</span>)]</span>
<span id="cb32-2"><a href="markov-chain-monte-carlo-mcmc.html#cb32-2" tabindex="-1"></a>mu_ci <span class="ot">&lt;-</span> <span class="fu">quantile</span>(sampling_vals<span class="sc">$</span>mu, <span class="fu">c</span>(.<span class="dv">025</span>, .<span class="dv">5</span>, .<span class="dv">975</span>))</span>
<span id="cb32-3"><a href="markov-chain-monte-carlo-mcmc.html#cb32-3" tabindex="-1"></a>sigma_ci <span class="ot">&lt;-</span> <span class="fu">quantile</span>(sampling_vals<span class="sc">$</span>sigma, <span class="fu">c</span>(.<span class="dv">025</span>, .<span class="dv">5</span>, .<span class="dv">975</span>))</span>
<span id="cb32-4"><a href="markov-chain-monte-carlo-mcmc.html#cb32-4" tabindex="-1"></a>ci <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fu">c</span>(.<span class="dv">025</span>, .<span class="dv">5</span>, .<span class="dv">975</span>), <span class="at">mean =</span> mu_ci[<span class="dv">2</span>], <span class="at">sd =</span> sigma_ci[<span class="dv">2</span>])</span>
<span id="cb32-5"><a href="markov-chain-monte-carlo-mcmc.html#cb32-5" tabindex="-1"></a></span>
<span id="cb32-6"><a href="markov-chain-monte-carlo-mcmc.html#cb32-6" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">temp =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">30</span>, <span class="at">by =</span> .<span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb32-7"><a href="markov-chain-monte-carlo-mcmc.html#cb32-7" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prob =</span> <span class="fu">map_dbl</span>(temp, <span class="sc">~</span><span class="fu">dnorm</span>(., <span class="at">mean =</span> ci[<span class="dv">2</span>], <span class="at">sd =</span> sigma_ci[<span class="dv">2</span>])),</span>
<span id="cb32-8"><a href="markov-chain-monte-carlo-mcmc.html#cb32-8" tabindex="-1"></a>         <span class="at">ci =</span> <span class="fu">if_else</span>(temp <span class="sc">&gt;=</span> ci[<span class="dv">1</span>] <span class="sc">&amp;</span> temp <span class="sc">&lt;=</span> ci[<span class="dv">3</span>], <span class="st">&quot;Y&quot;</span>, <span class="st">&quot;N&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb32-9"><a href="markov-chain-monte-carlo-mcmc.html#cb32-9" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> temp, <span class="at">y =</span> prob)) <span class="sc">+</span></span>
<span id="cb32-10"><a href="markov-chain-monte-carlo-mcmc.html#cb32-10" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">if_else</span>(ci <span class="sc">==</span> <span class="st">&quot;N&quot;</span>, prob, <span class="dv">0</span>)), </span>
<span id="cb32-11"><a href="markov-chain-monte-carlo-mcmc.html#cb32-11" tabindex="-1"></a>            <span class="at">fill =</span> <span class="st">&quot;firebrick&quot;</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb32-12"><a href="markov-chain-monte-carlo-mcmc.html#cb32-12" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb32-13"><a href="markov-chain-monte-carlo-mcmc.html#cb32-13" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> ci[<span class="dv">2</span>], <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb32-14"><a href="markov-chain-monte-carlo-mcmc.html#cb32-14" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb32-15"><a href="markov-chain-monte-carlo-mcmc.html#cb32-15" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">30</span>, <span class="dv">5</span>)) <span class="sc">+</span></span>
<span id="cb32-16"><a href="markov-chain-monte-carlo-mcmc.html#cb32-16" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb32-17"><a href="markov-chain-monte-carlo-mcmc.html#cb32-17" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Posterior temperature probability&quot;</span>, </span>
<span id="cb32-18"><a href="markov-chain-monte-carlo-mcmc.html#cb32-18" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="fu">glue</span>(<span class="st">&quot;mu = {ci[2] %&gt;% scales::number(accuracy = .1)}, 95%-CI (&quot;</span>,</span>
<span id="cb32-19"><a href="markov-chain-monte-carlo-mcmc.html#cb32-19" tabindex="-1"></a>       <span class="st">&quot;{ci[1] %&gt;% scales::number(accuracy = .1)}, &quot;</span>,</span>
<span id="cb32-20"><a href="markov-chain-monte-carlo-mcmc.html#cb32-20" tabindex="-1"></a>       <span class="st">&quot;{ci[3] %&gt;% scales::number(accuracy = .1)})&quot;</span>))</span></code></pre></div>
<p><img src="statistics_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>What is the probability the temperature is at least 18?</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="markov-chain-monte-carlo-mcmc.html#cb33-1" tabindex="-1"></a>pred_temp <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1000</span>, <span class="at">mean =</span> sampling_vals<span class="sc">$</span>mu, sampling_vals<span class="sc">$</span>sigma)</span>
<span id="cb33-2"><a href="markov-chain-monte-carlo-mcmc.html#cb33-2" tabindex="-1"></a>scales<span class="sc">::</span><span class="fu">percent</span>(<span class="fu">sum</span>(pred_temp <span class="sc">&gt;=</span> <span class="dv">18</span>) <span class="sc">/</span> <span class="fu">length</span>(pred_temp))</span></code></pre></div>
<pre><code>## [1] &quot;56%&quot;</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="markov-chain-monte-carlo-mcmc.html#cb35-1" tabindex="-1"></a>gibbs_normal <span class="ot">&lt;-</span> <span class="cf">function</span>(y, mu_0, tau_0, a, b, n_iter){</span>
<span id="cb35-2"><a href="markov-chain-monte-carlo-mcmc.html#cb35-2" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">length</span>(y)</span>
<span id="cb35-3"><a href="markov-chain-monte-carlo-mcmc.html#cb35-3" tabindex="-1"></a>  y_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(y)</span>
<span id="cb35-4"><a href="markov-chain-monte-carlo-mcmc.html#cb35-4" tabindex="-1"></a>  </span>
<span id="cb35-5"><a href="markov-chain-monte-carlo-mcmc.html#cb35-5" tabindex="-1"></a>  mu_sample <span class="ot">&lt;-</span> tau_sample <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n_iter)</span>
<span id="cb35-6"><a href="markov-chain-monte-carlo-mcmc.html#cb35-6" tabindex="-1"></a>  </span>
<span id="cb35-7"><a href="markov-chain-monte-carlo-mcmc.html#cb35-7" tabindex="-1"></a>  <span class="co"># starting values</span></span>
<span id="cb35-8"><a href="markov-chain-monte-carlo-mcmc.html#cb35-8" tabindex="-1"></a>  mu_sample[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">mean</span>(y)</span>
<span id="cb35-9"><a href="markov-chain-monte-carlo-mcmc.html#cb35-9" tabindex="-1"></a>  tau_sample[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> <span class="fu">var</span>(y)</span>
<span id="cb35-10"><a href="markov-chain-monte-carlo-mcmc.html#cb35-10" tabindex="-1"></a></span>
<span id="cb35-11"><a href="markov-chain-monte-carlo-mcmc.html#cb35-11" tabindex="-1"></a>  <span class="co"># Gibbs sampler</span></span>
<span id="cb35-12"><a href="markov-chain-monte-carlo-mcmc.html#cb35-12" tabindex="-1"></a>  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span>n_iter){</span>
<span id="cb35-13"><a href="markov-chain-monte-carlo-mcmc.html#cb35-13" tabindex="-1"></a>    <span class="co"># mu</span></span>
<span id="cb35-14"><a href="markov-chain-monte-carlo-mcmc.html#cb35-14" tabindex="-1"></a>    tau <span class="ot">&lt;-</span> tau_sample[i<span class="dv">-1</span>]</span>
<span id="cb35-15"><a href="markov-chain-monte-carlo-mcmc.html#cb35-15" tabindex="-1"></a>    mean_mu <span class="ot">&lt;-</span> (n <span class="sc">*</span> y_mean <span class="sc">*</span> tau <span class="sc">+</span> mu_0 <span class="sc">*</span> tau_0) <span class="sc">/</span> (n <span class="sc">*</span> tau <span class="sc">+</span> tau_0)</span>
<span id="cb35-16"><a href="markov-chain-monte-carlo-mcmc.html#cb35-16" tabindex="-1"></a>    precision_mu <span class="ot">&lt;-</span> n <span class="sc">*</span> tau <span class="sc">+</span> tau_0</span>
<span id="cb35-17"><a href="markov-chain-monte-carlo-mcmc.html#cb35-17" tabindex="-1"></a>    mu_sample[i] <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, mean_mu, <span class="dv">1</span> <span class="sc">/</span> <span class="fu">sqrt</span>(precision_mu))</span>
<span id="cb35-18"><a href="markov-chain-monte-carlo-mcmc.html#cb35-18" tabindex="-1"></a>    <span class="co"># tau</span></span>
<span id="cb35-19"><a href="markov-chain-monte-carlo-mcmc.html#cb35-19" tabindex="-1"></a>    mu <span class="ot">&lt;-</span> mu_sample[i<span class="dv">-1</span>]</span>
<span id="cb35-20"><a href="markov-chain-monte-carlo-mcmc.html#cb35-20" tabindex="-1"></a>    tau_sample[i] <span class="ot">&lt;-</span> <span class="fu">rgamma</span>(<span class="dv">1</span>, a <span class="sc">+</span> n<span class="sc">/</span><span class="dv">2</span>, b <span class="sc">+</span> .<span class="dv">5</span> <span class="sc">*</span> <span class="fu">sum</span>((y <span class="sc">-</span> mu)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb35-21"><a href="markov-chain-monte-carlo-mcmc.html#cb35-21" tabindex="-1"></a>  }</span>
<span id="cb35-22"><a href="markov-chain-monte-carlo-mcmc.html#cb35-22" tabindex="-1"></a>  </span>
<span id="cb35-23"><a href="markov-chain-monte-carlo-mcmc.html#cb35-23" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">list</span>(<span class="at">mu =</span> mu_sample, <span class="at">tau =</span> tau_sample))</span>
<span id="cb35-24"><a href="markov-chain-monte-carlo-mcmc.html#cb35-24" tabindex="-1"></a>}</span>
<span id="cb35-25"><a href="markov-chain-monte-carlo-mcmc.html#cb35-25" tabindex="-1"></a></span>
<span id="cb35-26"><a href="markov-chain-monte-carlo-mcmc.html#cb35-26" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb35-27"><a href="markov-chain-monte-carlo-mcmc.html#cb35-27" tabindex="-1"></a>sample_m <span class="ot">&lt;-</span> <span class="fu">gibbs_normal</span>(howell[howell<span class="sc">$</span>male <span class="sc">==</span> <span class="st">&quot;men&quot;</span>,]<span class="sc">$</span>height, <span class="dv">175</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">5</span><span class="sc">^</span><span class="dv">2</span>, .<span class="dv">01</span>, .<span class="dv">01</span>, <span class="dv">10</span><span class="sc">^</span><span class="dv">3</span>)</span></code></pre></div>
<pre><code>## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced

## Warning in rnorm(1, mean_mu, 1/sqrt(precision_mu)): NAs produced</code></pre>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="2">
<li id="fn2"><p>Some of these notes are from DataCamp course <a href="https://learn.datacamp.com/courses/fundamentals-of-bayesian-data-analysis-in-r">Fundamentals of Bayesian Data Analysis in R</a>.<a href="markov-chain-monte-carlo-mcmc.html#fnref2" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="bayesian-inference.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="gamma-poisson-and-estimating-counts.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="assets/gitbook-2.6.7/js/app.min.js"></script>
<script src="assets/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="assets/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection",
"scroll_highlight": true
},
"toolbar": {
"position": "static"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
